import type { TemplateChecklistItem } from "@/lib/types";

type ItemOptions = Partial<
  Omit<
    TemplateChecklistItem,
    | "id"
    | "name"
    | "category"
    | "priority"
    | "source"
    | "sourceLabel"
    | "editable"
    | "timing"
  >
>;

function templateItem(
  id: string,
  name: TemplateChecklistItem["name"],
  category: TemplateChecklistItem["category"],
  priority: TemplateChecklistItem["priority"],
  timing: TemplateChecklistItem["timing"],
  options: ItemOptions = {},
): TemplateChecklistItem {
  return {
    id,
    name,
    category,
    priority,
    source: "general",
    sourceLabel: "通用模板",
    editable: true,
    removable: true,
    timing,
    ...options,
  };
}

export const generalTemplate: TemplateChecklistItem[] = [
  templateItem("general-doc-id", "身份证件", "documents", "must", "pack_now", {
    removable: false,
    packTier: "core",
    itemKind: "item",
    bag: "documents_folder",
    bulk: "small",
  }),
  templateItem(
    "general-doc-medical-card",
    "医保卡 / 社保卡",
    "documents",
    "must",
    "pack_now",
    {
      removable: false,
      packTier: "core",
      itemKind: "item",
      bag: "documents_folder",
      bulk: "small",
    },
  ),
  templateItem(
    "general-doc-prenatal-records",
    "产检资料",
    "documents",
    "must",
    "pack_now",
    {
      removable: false,
      packTier: "core",
      itemKind: "item",
      bag: "documents_folder",
      bulk: "medium",
    },
  ),
  templateItem("general-doc-admission", "入院资料", "documents", "must", "pack_now", {
    removable: false,
    packTier: "core",
    itemKind: "item",
    bag: "documents_folder",
    bulk: "small",
  }),
  templateItem(
    "general-doc-cash",
    "少量现金，如医院 / 停车 / 食堂需要",
    "documents",
    "optional",
    "pack_now",
    {
      packTier: "optional",
      itemKind: "item",
      bag: "documents_folder",
      bulk: "small",
    },
  ),

  templateItem("general-labor-phone", "手机", "mom_labor", "must", "grab_before_leaving", {
    removable: false,
    packTier: "core",
    itemKind: "item",
    bag: "last_minute",
    bulk: "small",
  }),
  templateItem(
    "general-labor-long-cable",
    "长充电线",
    "mom_labor",
    "must",
    "pack_now",
    {
      packTier: "core",
      itemKind: "item",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-labor-toiletries",
    "洗漱用品",
    "mom_labor",
    "must",
    "pack_now",
    {
      note: "发圈/发夹可以放进洗漱包，按个人习惯准备即可。",
      packTier: "core",
      itemKind: "item",
      bag: "mom_bag",
      bulk: "medium",
    },
  ),
  templateItem("general-labor-lip-balm", "护唇膏", "mom_labor", "must", "pack_now", {
    packTier: "core",
    itemKind: "item",
    bag: "mom_bag",
    bulk: "small",
  }),
  templateItem("general-labor-cup", "水杯 / 吸管杯", "mom_labor", "must", "pack_now", {
    packTier: "core",
    itemKind: "item",
    bag: "mom_bag",
    bulk: "medium",
  }),
  templateItem(
    "general-labor-slippers",
    "防滑拖鞋 / 洗澡拖鞋",
    "mom_labor",
    "must",
    "pack_now",
    {
      packTier: "core",
      itemKind: "item",
      bag: "mom_bag",
      bulk: "medium",
    },
  ),
  templateItem(
    "general-labor-glasses",
    "眼镜 / 隐形眼镜用品，如适用",
    "mom_labor",
    "must",
    "grab_before_leaving",
    {
      packTier: "core",
      itemKind: "item",
      bag: "last_minute",
      bulk: "small",
    },
  ),
  templateItem(
    "general-labor-medicine-list",
    "常用药清单 / 医生确认用药",
    "mom_labor",
    "must",
    "grab_before_leaving",
    {
      note: "如有长期用药，请提前向医生或护士确认携带和使用方式。",
      packTier: "core",
      itemKind: "task",
      bag: "last_minute",
      bulk: "small",
    },
  ),
  templateItem(
    "general-labor-power-bank",
    "充电宝",
    "mom_labor",
    "optional",
    "pack_now",
    {
      packTier: "optional",
      itemKind: "item",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-labor-energy-food",
    "补能食品/饮料，按医院要求",
    "mom_labor",
    "optional",
    "pack_now",
    {
      note: "先确认产房和病区是否允许携带。",
      packTier: "optional",
      itemKind: "item",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem("general-labor-towels", "毛巾", "mom_labor", "optional", "wash_before_pack", {
    quantity: "按个人习惯",
    packTier: "optional",
    itemKind: "item",
    bag: "mom_bag",
    bulk: "medium",
  }),
  templateItem(
    "general-labor-clothes",
    "住院换洗衣物 / 前开睡衣",
    "mom_labor",
    "recommended",
    "wash_before_pack",
    {
      quantity: "1-2 套",
      packTier: "optional",
      itemKind: "item",
      bag: "mom_bag",
      bulk: "large",
    },
  ),
  templateItem("general-labor-socks", "袜子", "mom_labor", "optional", "wash_before_pack", {
    quantity: "1-2 双",
    packTier: "optional",
    itemKind: "item",
    bag: "mom_bag",
    bulk: "small",
  }),
  templateItem(
    "general-labor-tissues",
    "纸巾 / 湿巾",
    "mom_labor",
    "optional",
    "pack_now",
    {
      packTier: "optional",
      itemKind: "item",
      bag: "mom_bag",
      bulk: "small",
    },
  ),

  templateItem(
    "general-postpartum-pads",
    "产褥垫 / 产后卫生巾",
    "mom_postpartum",
    "must",
    "pack_now",
    {
      quantity: "少量备用",
      note: "按医院要求准备，已明确提供再标记为医院提供。",
      packTier: "core",
      itemKind: "item",
      bag: "mom_bag",
      bulk: "medium",
    },
  ),
  templateItem(
    "general-postpartum-underwear",
    "一次性内裤",
    "mom_postpartum",
    "must",
    "pack_now",
    {
      quantity: "按预计住院天数准备",
      packTier: "core",
      itemKind: "item",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-postpartum-going-home-clothes",
    "宽松出院衣物",
    "mom_postpartum",
    "must",
    "wash_before_pack",
    {
      packTier: "core",
      itemKind: "item",
      bag: "mom_bag",
      bulk: "large",
    },
  ),
  templateItem(
    "general-postpartum-storage-bags",
    "收纳袋 / 脏衣袋",
    "mom_postpartum",
    "must",
    "pack_now",
    {
      packTier: "core",
      itemKind: "item",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-postpartum-nursing-bra",
    "哺乳内衣",
    "mom_postpartum",
    "recommended",
    "wash_before_pack",
    {
      appliesTo: { breastfeeding: true },
      packTier: "core",
      itemKind: "item",
      bag: "mom_bag",
      bulk: "medium",
    },
  ),
  templateItem(
    "general-postpartum-breast-pads",
    "溢乳垫",
    "mom_postpartum",
    "optional",
    "pack_now",
    {
      appliesTo: { breastfeeding: true },
      packTier: "optional",
      itemKind: "item",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-postpartum-nipple-cream",
    "乳头膏",
    "mom_postpartum",
    "optional",
    "pack_now",
    {
      appliesTo: { breastfeeding: true },
      packTier: "optional",
      itemKind: "item",
      bag: "mom_bag",
      bulk: "small",
    },
  ),

  templateItem("general-baby-home-clothes", "宝宝出院衣物", "baby", "must", "wash_before_pack", {
    quantity: "1 套 + 备用 1 套",
    packTier: "core",
    itemKind: "item",
    bag: "baby_bag",
    bulk: "medium",
  }),
  templateItem("general-baby-blanket", "包被 / 小毯子", "baby", "must", "wash_before_pack", {
    note: "按季节准备，寒冷天气优先确认保暖。",
    packTier: "core",
    itemKind: "item",
    bag: "baby_bag",
    bulk: "large",
  }),
  templateItem("general-baby-diapers", "尿不湿", "baby", "must", "pack_now", {
    quantity: "少量备用",
    note: "按医院要求准备，已明确提供再标记为医院提供。",
    packTier: "core",
    itemKind: "item",
    bag: "baby_bag",
    bulk: "medium",
  }),
  templateItem("general-baby-wipes", "湿巾 / 棉柔巾", "baby", "must", "pack_now", {
    quantity: "少量备用",
    note: "按医院要求准备。",
    packTier: "core",
    itemKind: "item",
    bag: "baby_bag",
    bulk: "medium",
  }),
  templateItem("general-baby-hat", "宝宝帽子", "baby", "optional", "wash_before_pack", {
    packTier: "optional",
    itemKind: "item",
    bag: "baby_bag",
    bulk: "small",
  }),
  templateItem("general-baby-socks", "宝宝袜子", "baby", "optional", "wash_before_pack", {
    packTier: "optional",
    itemKind: "item",
    bag: "baby_bag",
    bulk: "small",
  }),
  templateItem(
    "general-baby-hospital-clothes",
    "宝宝住院衣物，如医院不提供",
    "baby",
    "optional",
    "wash_before_pack",
    {
      packTier: "optional",
      itemKind: "item",
      bag: "baby_bag",
      bulk: "medium",
    },
  ),
  templateItem("general-baby-towels", "口水巾 / 小方巾", "baby", "optional", "wash_before_pack", {
    packTier: "optional",
    itemKind: "item",
    bag: "baby_bag",
    bulk: "small",
  }),
  templateItem("general-baby-diaper-cream", "护臀膏", "baby", "optional", "pack_now", {
    packTier: "optional",
    itemKind: "item",
    bag: "baby_bag",
    bulk: "small",
  }),
  templateItem("general-baby-changing-pads", "一次性隔尿垫", "baby", "optional", "pack_now", {
    packTier: "optional",
    itemKind: "item",
    bag: "baby_bag",
    bulk: "medium",
  }),
  templateItem("general-baby-nail-clipper", "宝宝指甲剪", "baby", "optional", "pack_now", {
    packTier: "hidden",
    itemKind: "item",
    bag: "baby_bag",
    bulk: "small",
  }),

  templateItem(
    "general-partner-save-phone",
    "保存产科/住院处电话",
    "partner",
    "must",
    "confirm_with_hospital",
    {
      appliesTo: { partnerPresent: true },
      packTier: "core",
      itemKind: "task",
      bag: "none",
      bulk: "small",
    },
  ),
  templateItem(
    "general-partner-night-entrance",
    "确认夜间入院入口",
    "partner",
    "must",
    "confirm_with_hospital",
    {
      appliesTo: { partnerPresent: true },
      packTier: "core",
      itemKind: "task",
      bag: "none",
      bulk: "small",
    },
  ),
  templateItem(
    "general-partner-parking-plan",
    "确认停车方案",
    "partner",
    "must",
    "confirm_with_hospital",
    {
      appliesTo: { partnerPresent: true },
      packTier: "core",
      itemKind: "task",
      bag: "car",
      bulk: "small",
    },
  ),
  templateItem(
    "general-partner-doc-folder",
    "确认证件包位置",
    "partner",
    "must",
    "pack_now",
    {
      appliesTo: { partnerPresent: true },
      packTier: "core",
      itemKind: "task",
      bag: "documents_folder",
      bulk: "small",
    },
  ),
  templateItem(
    "general-partner-payment",
    "确认支付方式和住院押金",
    "partner",
    "must",
    "confirm_with_hospital",
    {
      note: "支付方式、住院押金和医保结算属于入院确认事项，不算待产包物品。若医院明确要求实体银行卡或现金，再作为自定义物品加入证件包。",
      appliesTo: { partnerPresent: true },
      packTier: "core",
      itemKind: "task",
      bag: "none",
      bulk: "small",
    },
  ),
  templateItem(
    "general-partner-car-seat",
    "确认安全座椅安装",
    "partner",
    "must",
    "pack_now",
    {
      appliesTo: { partnerPresent: true },
      packTier: "core",
      itemKind: "task",
      bag: "car",
      bulk: "large",
    },
  ),
  templateItem(
    "general-partner-family-notice",
    "临出门通知家人/紧急联系人",
    "partner",
    "recommended",
    "grab_before_leaving",
    {
      appliesTo: { partnerPresent: true },
      packTier: "core",
      itemKind: "task",
      bag: "last_minute",
      bulk: "small",
    },
  ),
  templateItem(
    "general-partner-id",
    "陪产人身份证件",
    "partner",
    "must",
    "grab_before_leaving",
    {
      appliesTo: { partnerPresent: true },
      packTier: "core",
      itemKind: "item",
      bag: "dad_backpack",
      bulk: "small",
    },
  ),
  templateItem(
    "general-partner-charger",
    "手机充电器",
    "partner",
    "must",
    "pack_now",
    {
      appliesTo: { partnerPresent: true },
      packTier: "core",
      itemKind: "item",
      bag: "dad_backpack",
      bulk: "small",
    },
  ),
  templateItem("general-partner-water-snacks", "水和零食", "partner", "recommended", "pack_now", {
    appliesTo: { partnerPresent: true },
    packTier: "core",
    itemKind: "item",
    bag: "dad_backpack",
    bulk: "medium",
  }),
  templateItem(
    "general-partner-clothes",
    "换洗衣物 1 套，如需过夜",
    "partner",
    "recommended",
    "wash_before_pack",
    {
      appliesTo: { partnerPresent: true },
      packTier: "core",
      itemKind: "item",
      bag: "dad_backpack",
      bulk: "medium",
    },
  ),
  templateItem(
    "general-partner-toiletries",
    "洗漱用品，如需过夜",
    "partner",
    "recommended",
    "pack_now",
    {
      appliesTo: { partnerPresent: true },
      packTier: "core",
      itemKind: "item",
      bag: "dad_backpack",
      bulk: "small",
    },
  ),
  templateItem(
    "general-partner-glasses",
    "眼镜 / 隐形眼镜用品",
    "partner",
    "optional",
    "grab_before_leaving",
    {
      appliesTo: { partnerPresent: true },
      packTier: "optional",
      itemKind: "item",
      bag: "dad_backpack",
      bulk: "small",
    },
  ),
  templateItem(
    "general-partner-medicine-list",
    "个人常用药清单 / 按需确认",
    "partner",
    "optional",
    "grab_before_leaving",
    {
      note: "如有长期用药，按个人情况提前确认。",
      appliesTo: { partnerPresent: true },
      packTier: "optional",
      itemKind: "task",
      bag: "dad_backpack",
      bulk: "small",
    },
  ),

  templateItem(
    "general-going-home-mom-clothes",
    "妈妈出院衣物",
    "going_home",
    "must",
    "wash_before_pack",
    {
      packTier: "core",
      itemKind: "item",
      bag: "mom_bag",
      bulk: "large",
    },
  ),
  templateItem(
    "general-going-home-baby-clothes",
    "宝宝出院衣物",
    "going_home",
    "must",
    "wash_before_pack",
    {
      packTier: "core",
      itemKind: "item",
      bag: "baby_bag",
      bulk: "medium",
    },
  ),
  templateItem("general-going-home-blanket", "包被 / 小毯子", "going_home", "must", "wash_before_pack", {
    packTier: "core",
    itemKind: "item",
    bag: "baby_bag",
    bulk: "large",
  }),
  templateItem(
    "general-going-home-transport",
    "返家交通安排",
    "going_home",
    "must",
    "confirm_with_hospital",
    {
      packTier: "core",
      itemKind: "task",
      bag: "car",
      bulk: "small",
    },
  ),
  templateItem(
    "general-going-home-car-seat",
    "安全座椅确认",
    "going_home",
    "must",
    "pack_now",
    {
      packTier: "core",
      itemKind: "task",
      bag: "car",
      bulk: "large",
    },
  ),

  templateItem(
    "general-question-pads",
    "医院是否提供产褥垫？",
    "hospital_questions",
    "must",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-diapers",
    "医院是否提供宝宝尿不湿？",
    "hospital_questions",
    "must",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-baby-clothes",
    "医院是否提供宝宝衣物？",
    "hospital_questions",
    "must",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-partner",
    "医院是否允许陪产？",
    "hospital_questions",
    "must",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-partner-id",
    "陪产人是否需要身份证件或其他核验？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-deposit",
    "住院押金和医保结算方式是否已确认？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-entrance",
    "入院从哪个门进入？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-night-route",
    "夜间入院入口和急诊入院路线是否已确认？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-parking",
    "停车是否方便？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-phone",
    "产科 / 住院处联系电话是否已保存？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-bed",
    "是否需要提前预约床位或办理住院手续？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-not-allowed",
    "医院是否有不建议携带的物品？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-energy-food",
    "产房是否允许带补能食品/饮料？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-baby-hospital-clothes",
    "宝宝住院衣物是否需要自带？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-tableware",
    "是否需要自带餐具/饭盒/筷勺？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-breast-pump",
    "吸奶器是否需要带？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    {
      appliesTo: { breastfeeding: true },
      removable: false,
      packTier: "confirm",
      itemKind: "question",
      bag: "none",
    },
  ),
  templateItem(
    "general-question-birth-certificate",
    "出生医学证明办理需要哪些材料？父母双方身份证、结婚证、户口本是否需要？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", bag: "none" },
  ),

  templateItem("general-last-id", "身份证件", "last_minute", "must", "grab_before_leaving", {
    removable: false,
    packTier: "core",
    itemKind: "task",
    bag: "last_minute",
    bulk: "small",
  }),
  templateItem(
    "general-last-medical-card",
    "医保卡 / 社保卡",
    "last_minute",
    "must",
    "grab_before_leaving",
    {
      removable: false,
      packTier: "core",
      itemKind: "task",
      bag: "last_minute",
      bulk: "small",
    },
  ),
  templateItem(
    "general-last-maternal-book",
    "北京市母子健康手册或本地区孕产资料",
    "last_minute",
    "must",
    "grab_before_leaving",
    {
      removable: false,
      packTier: "core",
      itemKind: "task",
      bag: "last_minute",
      bulk: "small",
    },
  ),
  templateItem(
    "general-last-prenatal-records",
    "产检资料",
    "last_minute",
    "must",
    "grab_before_leaving",
    {
      removable: false,
      packTier: "core",
      itemKind: "task",
      bag: "last_minute",
      bulk: "medium",
    },
  ),
  templateItem("general-last-phone", "手机", "last_minute", "must", "grab_before_leaving", {
    removable: false,
    packTier: "core",
    itemKind: "task",
    bag: "last_minute",
    bulk: "small",
  }),
  templateItem("general-last-charger", "充电器", "last_minute", "must", "grab_before_leaving", {
    removable: false,
    packTier: "core",
    itemKind: "task",
    bag: "last_minute",
    bulk: "small",
  }),
  templateItem(
    "general-last-medicine-list",
    "常用药清单 / 医生确认用药",
    "last_minute",
    "must",
    "grab_before_leaving",
    {
      note: "如有长期用药，请提前向医生或护士确认携带和使用方式。",
      removable: false,
      packTier: "core",
      itemKind: "task",
      bag: "last_minute",
      bulk: "small",
    },
  ),
  templateItem(
    "general-last-glasses",
    "眼镜 / 隐形眼镜",
    "last_minute",
    "must",
    "grab_before_leaving",
    {
      removable: false,
      packTier: "core",
      itemKind: "task",
      bag: "last_minute",
      bulk: "small",
    },
  ),
  templateItem(
    "general-last-payment",
    "支付 / 押金确认",
    "last_minute",
    "must",
    "grab_before_leaving",
    {
      removable: false,
      packTier: "core",
      itemKind: "task",
      bag: "none",
      bulk: "small",
    },
  ),
  templateItem(
    "general-last-car-seat",
    "安全座椅确认",
    "last_minute",
    "must",
    "grab_before_leaving",
    {
      removable: false,
      packTier: "core",
      itemKind: "task",
      bag: "car",
      bulk: "large",
    },
  ),
  templateItem(
    "general-last-home-check",
    "关水电燃气/门窗检查",
    "last_minute",
    "must",
    "grab_before_leaving",
    {
      removable: true,
      packTier: "core",
      itemKind: "task",
      bag: "last_minute",
      bulk: "small",
    },
  ),
];
