import type { TemplateChecklistItem } from "@/lib/types";

type ItemOptions = Partial<
  Omit<
    TemplateChecklistItem,
    | "id"
    | "name"
    | "category"
    | "priority"
    | "source"
    | "sourceLabel"
    | "editable"
    | "timing"
  >
>;

function templateItem(
  id: string,
  name: TemplateChecklistItem["name"],
  category: TemplateChecklistItem["category"],
  priority: TemplateChecklistItem["priority"],
  timing: TemplateChecklistItem["timing"],
  options: ItemOptions = {},
): TemplateChecklistItem {
  return {
    id,
    name,
    category,
    priority,
    source: "general",
    sourceLabel: "通用模板",
    editable: true,
    removable: true,
    timing,
    ...options,
  };
}

export const generalTemplate: TemplateChecklistItem[] = [
  templateItem("general-doc-id", "身份证件", "documents", "must", "pack_now", {
    note: "夫妻双方身份证原件 + 复印件，入院登记和办出生证明都要用。",
    removable: false,
    packTier: "core",
    itemKind: "item",
    preparationKind: "document",
    bag: "documents_folder",
    bulk: "small",
  }),
  templateItem(
    "general-doc-medical-card",
    "医保卡 / 社保卡",
    "documents",
    "must",
    "pack_now",
    {
      note: "确认卡状态正常，电子医保凭证截图备份一份。",
      removable: false,
      packTier: "core",
      itemKind: "item",
      preparationKind: "document",
      bag: "documents_folder",
      bulk: "small",
    },
  ),
  templateItem(
    "general-doc-prenatal-records",
    "产检资料",
    "documents",
    "must",
    "pack_now",
    {
      note: "产检本、B 超单、化验单按时间顺序装好，入院时医生要查看。",
      removable: false,
      packTier: "core",
      itemKind: "item",
      preparationKind: "document",
      bag: "documents_folder",
      bulk: "medium",
    },
  ),
  templateItem("general-doc-admission", "入院资料", "documents", "must", "pack_now", {
    note: "住院证、入院通知单等医院开具的材料，与产检资料放在一起。",
    removable: false,
    packTier: "core",
    itemKind: "item",
    preparationKind: "document",
    bag: "documents_folder",
    bulk: "small",
  }),
  templateItem(
    "general-doc-birth-plan",
    "分娩偏好卡 / 出生计划",
    "documents",
    "recommended",
    "pack_now",
    {
      note: "如已整理分娩偏好、用药过敏、陪产人和紧急联系人，可与产检资料放在一起。",
      packTier: "core",
      itemKind: "item",
      preparationKind: "document",
      bag: "documents_folder",
      bulk: "small",
    },
  ),
  templateItem(
    "general-doc-cash",
    "少量现金，如医院 / 停车 / 食堂需要",
    "documents",
    "optional",
    "pack_now",
    {
      note: "备 200-500 元零钱即可，大部分场景可以手机支付。",
      packTier: "optional",
      itemKind: "item",
      bag: "documents_folder",
      bulk: "small",
    },
  ),
  templateItem("general-doc-marriage-cert", "结婚证", "documents", "recommended", "pack_now", {
    note: "办理出生医学证明时多数医院需要，与户口本放在一起。",
    packTier: "core",
    itemKind: "item",
    preparationKind: "document",
    bag: "documents_folder",
    bulk: "small",
  }),
  templateItem("general-doc-hukou", "户口本", "documents", "recommended", "pack_now", {
    note: "办理出生医学证明时多数医院需要，与结婚证放在一起。",
    packTier: "core",
    itemKind: "item",
    preparationKind: "document",
    bag: "documents_folder",
    bulk: "small",
  }),
  templateItem(
    "general-doc-birth-registration",
    "生育服务单 / 生育登记凭证",
    "documents",
    "recommended",
    "pack_now",
    {
      note: "各地名称不同，按本地区要求准备。",
      packTier: "core",
      itemKind: "item",
      preparationKind: "document",
      bag: "documents_folder",
      bulk: "small",
    },
  ),
  templateItem("general-doc-bank-card", "银行卡", "documents", "recommended", "pack_now", {
    note: "住院押金、自费项目备用，顺便确认手机支付限额。",
    packTier: "core",
    itemKind: "item",
    preparationKind: "document",
    bag: "documents_folder",
    bulk: "small",
  }),

  templateItem("general-labor-phone", "手机", "mom_labor", "must", "grab_before_leaving", {
    note: "提前存好产科、住院处电话和家人紧急联系人。",
    removable: false,
    packTier: "core",
    itemKind: "item",
    preparationKind: "last_minute",
    bag: "last_minute",
    bulk: "small",
  }),
  templateItem(
    "general-labor-long-cable",
    "长充电线",
    "mom_labor",
    "must",
    "pack_now",
    {
      note: "病床插座常离床头较远，建议 2 米以上。",
      packTier: "core",
      itemKind: "item",
      preparationKind: "pack_existing",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-labor-toiletries",
    "洗漱用品",
    "mom_labor",
    "must",
    "pack_now",
    {
      note: "发圈/发夹可以放进洗漱包，按个人习惯准备即可。",
      packTier: "core",
      itemKind: "item",
      preparationKind: "pack_existing",
      bag: "mom_bag",
      bulk: "medium",
    },
  ),
  templateItem("general-labor-lip-balm", "护唇膏", "mom_labor", "must", "pack_now", {
    note: "产程张口呼吸、病房空调干燥，嘴唇容易干裂。",
    packTier: "core",
    itemKind: "item",
    preparationKind: "pack_existing",
    bag: "mom_bag",
    bulk: "small",
  }),
  templateItem("general-labor-cup", "水杯 / 吸管杯", "mom_labor", "must", "pack_now", {
    note: "躺卧姿势也能喝水，产程和产后都高频使用。",
    packTier: "core",
    itemKind: "item",
    preparationKind: "pack_existing",
    bag: "mom_bag",
    bulk: "medium",
  }),
  templateItem("general-labor-eye-mask", "眼罩", "mom_labor", "optional", "pack_now", {
    note: "病房灯光较亮时可帮助休息。",
    packTier: "optional",
    itemKind: "item",
    preparationKind: "pack_existing",
    bag: "mom_bag",
    bulk: "small",
  }),
  templateItem(
    "general-labor-pillow",
    "自用枕头，如需要",
    "mom_labor",
    "optional",
    "pack_now",
    {
      note: "如携带，建议使用明显不同于医院床品的枕套。",
      packTier: "optional",
      itemKind: "item",
      preparationKind: "pack_existing",
      bag: "mom_bag",
      bulk: "large",
    },
  ),
  templateItem(
    "general-labor-cooling",
    "小风扇 / 喷雾瓶",
    "mom_labor",
    "optional",
    "pack_now",
    {
      note: "用于产程中降温，先确认医院是否允许携带。",
      packTier: "optional",
      itemKind: "item",
      preparationKind: "pack_existing",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-labor-relaxation",
    "耳机 / 放松音频",
    "mom_labor",
    "optional",
    "grab_before_leaving",
    {
      note: "音乐、播客或冥想音频按个人习惯准备。",
      packTier: "optional",
      itemKind: "item",
      preparationKind: "last_minute",
      bag: "last_minute",
      bulk: "small",
    },
  ),
  templateItem(
    "general-labor-tens",
    "TENS 镇痛仪，如已决定使用",
    "mom_labor",
    "optional",
    "pack_now",
    {
      note: "仅在医生或助产士允许且自己已决定使用时携带，记得备用电池。",
      packTier: "optional",
      itemKind: "item",
      preparationKind: "pack_existing",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-labor-slippers",
    "防滑拖鞋 / 洗澡拖鞋",
    "mom_labor",
    "must",
    "pack_now",
    {
      note: "产后身体虚弱、卫生间地面湿滑，防滑优先。",
      packTier: "core",
      itemKind: "item",
      preparationKind: "pack_existing",
      bag: "mom_bag",
      bulk: "medium",
    },
  ),
  templateItem(
    "general-labor-glasses",
    "眼镜 / 隐形眼镜用品，如适用",
    "mom_labor",
    "must",
    "grab_before_leaving",
    {
      note: "近视妈妈备一副框架眼镜，待产和产后不建议戴隐形眼镜。",
      packTier: "core",
      itemKind: "item",
      preparationKind: "last_minute",
      bag: "last_minute",
      bulk: "small",
    },
  ),
  templateItem(
    "general-labor-medicine-list",
    "常用药清单 / 医生确认用药",
    "mom_labor",
    "must",
    "grab_before_leaving",
    {
      note: "如有长期用药，请提前向医生或护士确认携带和使用方式。",
      packTier: "core",
      itemKind: "task",
      preparationKind: "last_minute",
      bag: "last_minute",
      bulk: "small",
    },
  ),
  templateItem(
    "general-labor-power-bank",
    "充电宝",
    "mom_labor",
    "optional",
    "pack_now",
    {
      note: "待产和住院时间长，插座紧张时兜底。",
      packTier: "optional",
      itemKind: "item",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-labor-energy-food",
    "补能食品/饮料，按医院要求",
    "mom_labor",
    "optional",
    "pack_now",
    {
      note: "先确认产房和病区是否允许携带。",
      packTier: "optional",
      itemKind: "item",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem("general-labor-towels", "毛巾", "mom_labor", "optional", "wash_before_pack", {
    quantity: "按个人习惯",
    note: "擦汗、擦身分开用，建议 2 条以上。",
    packTier: "optional",
    itemKind: "item",
    bag: "mom_bag",
    bulk: "medium",
  }),
  templateItem(
    "general-labor-clothes",
    "住院换洗衣物 / 前开睡衣",
    "mom_labor",
    "recommended",
    "wash_before_pack",
    {
      quantity: "2-3 套",
      note: "前开扣方便哺乳和胎心监护。",
      packTier: "optional",
      itemKind: "item",
      bag: "mom_bag",
      bulk: "large",
    },
  ),
  templateItem("general-labor-socks", "袜子", "mom_labor", "optional", "wash_before_pack", {
    quantity: "1-2 双",
    note: "产房和病房空调足，备宽松棉袜护住脚踝。",
    packTier: "optional",
    itemKind: "item",
    bag: "mom_bag",
    bulk: "small",
  }),
  templateItem(
    "general-labor-tissues",
    "纸巾 / 湿巾",
    "mom_labor",
    "optional",
    "pack_now",
    {
      quantity: "各 1-2 包",
      note: "选无香型，宝宝用的另备婴儿专用款。",
      packTier: "optional",
      itemKind: "item",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-labor-ctg-belt",
    "胎心监护带",
    "mom_labor",
    "recommended",
    "pack_now",
    {
      quantity: "2 条",
      note: "部分医院要求自带，产检时先确认；常备两条装。",
      packTier: "core",
      itemKind: "item",
      preparationKind: "buy_and_pack",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-labor-straws",
    "一次性吸管",
    "mom_labor",
    "recommended",
    "pack_now",
    {
      quantity: "1 包（约 30 根）",
      note: "躺着喝水、喝粥都靠它，选独立包装更卫生。",
      packTier: "core",
      itemKind: "item",
      preparationKind: "buy_and_pack",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-labor-tableware",
    "餐具 / 饭盒筷勺",
    "mom_labor",
    "optional",
    "pack_now",
    {
      quantity: "1 套",
      note: "部分医院订餐不配餐具；带盖保温饭盒家属送饭也用得上。",
      packTier: "optional",
      itemKind: "item",
      preparationKind: "wash_then_pack",
      bag: "mom_bag",
      bulk: "medium",
    },
  ),
  templateItem(
    "general-labor-moon-toothbrush",
    "月子牙刷 / 漱口水",
    "mom_labor",
    "recommended",
    "pack_now",
    {
      quantity: "牙刷 1 支 + 漱口水 1 小瓶",
      note: "产后牙龈敏感，选软毛月子牙刷；不便刷牙时先用漱口水。",
      packTier: "core",
      itemKind: "item",
      preparationKind: "buy_and_pack",
      bag: "mom_bag",
      bulk: "small",
    },
  ),

  templateItem(
    "general-postpartum-pads",
    "产褥垫 / 产后卫生巾",
    "mom_postpartum",
    "must",
    "pack_now",
    {
      quantity: "10-20 片",
      note: "按医院要求准备，产房和产后恶露期都要用，已明确提供再标记为医院提供。",
      packTier: "core",
      itemKind: "item",
      preparationKind: "buy_and_pack",
      bag: "mom_bag",
      bulk: "medium",
    },
  ),
  templateItem("general-postpartum-paper", "刀纸 / 产褥卫生纸", "mom_postpartum", "must", "pack_now", {
    quantity: "1-2 提",
    note: "产房和产后恶露期高频消耗品，部分医院要求自带。",
    packTier: "core",
    itemKind: "item",
    preparationKind: "buy_and_pack",
    bag: "mom_bag",
    bulk: "medium",
  }),
  templateItem(
    "general-postpartum-metered-pads",
    "计量型卫生巾",
    "mom_postpartum",
    "recommended",
    "pack_now",
    {
      note: "产后 24 小时出血量观察用，按医院要求准备。",
      packTier: "optional",
      itemKind: "item",
      preparationKind: "buy_and_pack",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-postpartum-underwear",
    "一次性内裤",
    "mom_postpartum",
    "must",
    "pack_now",
    {
      quantity: "5-6 条或按预计住院天数准备",
      note: "产后恶露期每天更换，免洗更卫生。",
      packTier: "core",
      itemKind: "item",
      preparationKind: "buy_and_pack",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-postpartum-toilet-seat-covers",
    "一次性马桶垫",
    "mom_postpartum",
    "recommended",
    "pack_now",
    {
      quantity: "10-20 片",
      note: "病房公用马桶的卫生防护。",
      packTier: "optional",
      itemKind: "item",
      preparationKind: "buy_and_pack",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-postpartum-yuezi-hat-shoes",
    "月子帽 / 月子鞋",
    "mom_postpartum",
    "optional",
    "wash_before_pack",
    {
      note: "按季节和个人习惯准备，非必需。",
      packTier: "optional",
      itemKind: "item",
      preparationKind: "wash_then_pack",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-postpartum-going-home-clothes",
    "宽松出院衣物",
    "mom_postpartum",
    "must",
    "wash_before_pack",
    {
      quantity: "1 套",
      note: "按出院季节备一套宽松外套，肚子还没恢复，别拿孕前尺码。",
      packTier: "core",
      itemKind: "item",
      preparationKind: "wash_then_pack",
      bag: "mom_bag",
      bulk: "large",
    },
  ),
  templateItem(
    "general-postpartum-storage-bags",
    "收纳袋 / 脏衣袋",
    "mom_postpartum",
    "must",
    "pack_now",
    {
      quantity: "3-5 个",
      note: "分装干净和脏衣物，备几个不同大小的密封袋。",
      packTier: "core",
      itemKind: "item",
      preparationKind: "pack_existing",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-postpartum-nursing-bra",
    "哺乳内衣",
    "mom_postpartum",
    "recommended",
    "wash_before_pack",
    {
      appliesTo: { breastfeeding: true },
      quantity: "2-3 件",
      note: "前开扣款方便喂奶，按涨奶后的尺码选大一号。",
      packTier: "core",
      itemKind: "item",
      preparationKind: "wash_then_pack",
      bag: "mom_bag",
      bulk: "medium",
    },
  ),
  templateItem(
    "general-postpartum-breast-pads",
    "溢乳垫",
    "mom_postpartum",
    "optional",
    "pack_now",
    {
      appliesTo: { breastfeeding: true },
      note: "涨奶和漏奶时保持衣物干爽。",
      packTier: "optional",
      itemKind: "item",
      preparationKind: "buy_and_pack",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-postpartum-nipple-cream",
    "乳头膏",
    "mom_postpartum",
    "optional",
    "pack_now",
    {
      appliesTo: { breastfeeding: true },
      note: "哺乳初期乳头皲裂常见，提前备一支。",
      packTier: "optional",
      itemKind: "item",
      preparationKind: "buy_and_pack",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-postpartum-pull-up-pants",
    "产妇拉拉裤 / 安心裤",
    "mom_postpartum",
    "recommended",
    "pack_now",
    {
      quantity: "1 包（5-8 片）",
      note: "产后头两天恶露多，拉拉裤穿脱比普通卫生巾方便；医院提供则不重复带。",
      packTier: "core",
      itemKind: "item",
      preparationKind: "buy_and_pack",
      bag: "mom_bag",
      bulk: "medium",
    },
  ),
  templateItem(
    "general-postpartum-peri-bottle",
    "私处冲洗器",
    "mom_postpartum",
    "recommended",
    "pack_now",
    {
      quantity: "1 个",
      note: "顺产撕裂或侧切后温水冲洗代替擦拭，选弯头款更顺手。",
      packTier: "core",
      itemKind: "item",
      preparationKind: "buy_and_pack",
      bag: "mom_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-postpartum-belly-wrap",
    "收腹带",
    "mom_postpartum",
    "optional",
    "pack_now",
    {
      quantity: "1 条",
      note: "剖腹产固定伤口、下床活动时用；顺产是否使用听医生建议。",
      packTier: "optional",
      itemKind: "item",
      preparationKind: "buy_and_pack",
      bag: "mom_bag",
      bulk: "medium",
    },
  ),
  templateItem(
    "general-postpartum-breast-pump",
    "吸奶器",
    "mom_postpartum",
    "recommended",
    "pack_now",
    {
      appliesTo: { breastfeeding: true },
      quantity: "1 套",
      note: "涨奶或宝宝不在身边时使用；电动款提前充好电，配件清洗消毒后装袋。",
      packTier: "core",
      itemKind: "item",
      preparationKind: "wash_then_pack",
      bag: "mom_bag",
      bulk: "medium",
    },
  ),
  templateItem(
    "general-postpartum-milk-bags",
    "储奶袋",
    "mom_postpartum",
    "optional",
    "pack_now",
    {
      appliesTo: { breastfeeding: true },
      quantity: "1 盒（约 30 片）",
      note: "多挤的初乳标注日期冷藏，先备一小盒即可。",
      packTier: "optional",
      itemKind: "item",
      preparationKind: "buy_and_pack",
      bag: "mom_bag",
      bulk: "small",
    },
  ),

  templateItem("general-baby-home-clothes", "宝宝出院衣物", "baby", "must", "wash_before_pack", {
    quantity: "1 套 + 备用 1 套",
    note: "52 码连体衣，按季节加减包被厚度。",
    packTier: "core",
    itemKind: "item",
    preparationKind: "wash_then_pack",
    bag: "baby_bag",
    bulk: "medium",
  }),
  templateItem("general-baby-blanket", "包被 / 小毯子", "baby", "must", "wash_before_pack", {
    note: "按季节准备，寒冷天气优先确认保暖。",
    packTier: "core",
    itemKind: "item",
    preparationKind: "wash_then_pack",
    bag: "baby_bag",
    bulk: "large",
  }),
  templateItem("general-baby-diapers", "尿不湿", "baby", "must", "pack_now", {
    quantity: "每天 8-10 片，按住院天数估算",
    note: "按医院要求准备，新生儿选 NB 码，已明确提供再标记为医院提供。",
    packTier: "core",
    itemKind: "item",
    preparationKind: "buy_and_pack",
    bag: "baby_bag",
    bulk: "medium",
  }),
  templateItem("general-baby-wipes", "湿巾 / 棉柔巾", "baby", "must", "pack_now", {
    quantity: "1-2 包",
    note: "按医院要求准备。",
    packTier: "core",
    itemKind: "item",
    preparationKind: "buy_and_pack",
    bag: "baby_bag",
    bulk: "medium",
  }),
  templateItem("general-baby-hat", "宝宝帽子", "baby", "optional", "wash_before_pack", {
    note: "出院路上防风保暖，按季节选择厚薄。",
    packTier: "optional",
    itemKind: "item",
    preparationKind: "wash_then_pack",
    bag: "baby_bag",
    bulk: "small",
  }),
  templateItem("general-baby-socks", "宝宝袜子", "baby", "optional", "wash_before_pack", {
    note: "按季节准备，出院时保暖。",
    packTier: "optional",
    itemKind: "item",
    preparationKind: "wash_then_pack",
    bag: "baby_bag",
    bulk: "small",
  }),
  templateItem(
    "general-baby-hospital-clothes",
    "宝宝住院衣物（连体衣/和尚服），如医院不提供",
    "baby",
    "optional",
    "wash_before_pack",
    {
      quantity: "2-3 套",
      note: "部分医院统一提供宝宝衣物，先确认再决定带几套。",
      packTier: "optional",
      itemKind: "item",
      preparationKind: "wash_then_pack",
      bag: "baby_bag",
      bulk: "medium",
    },
  ),
  templateItem("general-baby-towels", "纱布巾 / 小方巾", "baby", "optional", "wash_before_pack", {
    quantity: "3-5 条",
    note: "拍嗝、擦口水、垫着喂奶都用得上，多备几条。",
    packTier: "optional",
    itemKind: "item",
    preparationKind: "wash_then_pack",
    bag: "baby_bag",
    bulk: "small",
  }),
  templateItem("general-baby-diaper-cream", "护臀膏", "baby", "optional", "pack_now", {
    note: "红屁屁预防，每次换尿布后可薄涂。",
    packTier: "optional",
    itemKind: "item",
    bag: "baby_bag",
    bulk: "small",
  }),
  templateItem("general-baby-changing-pads", "一次性隔尿垫", "baby", "optional", "pack_now", {
    quantity: "10-20 片",
    note: "换尿布时垫在下面，脏了直接扔。",
    packTier: "optional",
    itemKind: "item",
    preparationKind: "buy_and_pack",
    bag: "baby_bag",
    bulk: "medium",
  }),
  templateItem(
    "general-baby-formula-bottle",
    "小罐奶粉 + 奶瓶 / 硅胶小勺（备用）",
    "baby",
    "optional",
    "confirm_with_hospital",
    {
      note: "母乳不足时的备用方案；爱婴医院常禁止自带奶粉奶瓶，先问清政策再决定。",
      packTier: "confirm",
      itemKind: "item",
      preparationKind: "buy_and_pack",
      bag: "baby_bag",
      bulk: "medium",
    },
  ),
  templateItem("general-baby-nail-clipper", "宝宝指甲剪", "baby", "optional", "pack_now", {
    quantity: "1 个",
    note: "新生儿指甲软但长得快，选圆头婴儿专用剪。",
    packTier: "hidden",
    itemKind: "item",
    bag: "baby_bag",
    bulk: "small",
  }),
  templateItem(
    "general-baby-navel-care",
    "护脐贴 + 碘伏棉签",
    "baby",
    "recommended",
    "pack_now",
    {
      quantity: "各 1 盒",
      note: "脐带脱落前保持干燥，洗澡贴护脐贴；消毒遵医嘱用碘伏棉签。",
      packTier: "core",
      itemKind: "item",
      preparationKind: "buy_and_pack",
      bag: "baby_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-baby-cotton-swabs",
    "婴儿细轴棉签",
    "baby",
    "optional",
    "pack_now",
    {
      quantity: "1 盒",
      note: "清理鼻腔、耳廓外侧用，选婴儿专用细轴款，不要伸进深处。",
      packTier: "optional",
      itemKind: "item",
      preparationKind: "buy_and_pack",
      bag: "baby_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-baby-lotion",
    "婴儿润肤霜 / 抚触油",
    "baby",
    "optional",
    "pack_now",
    {
      quantity: "1 小瓶",
      note: "秋冬干燥或洗澡后做抚触用，选无香型、成分简单款。",
      packTier: "optional",
      itemKind: "item",
      preparationKind: "buy_and_pack",
      bag: "baby_bag",
      bulk: "small",
    },
  ),
  templateItem(
    "general-baby-bottle-brush",
    "奶瓶刷 + 小瓶清洗剂",
    "baby",
    "optional",
    "pack_now",
    {
      quantity: "各 1",
      note: "备用奶瓶每次用完及时刷洗晾干，清洗剂选婴幼儿专用。",
      packTier: "optional",
      itemKind: "item",
      preparationKind: "buy_and_pack",
      bag: "baby_bag",
      bulk: "small",
    },
  ),

  templateItem(
    "general-partner-save-phone",
    "保存产科/住院处电话",
    "partner",
    "must",
    "confirm_with_hospital",
    {
      appliesTo: { partnerPresent: true },
      note: "产科病房、住院处、急诊电话存入手机并置顶，家人群也发一份。",
      packTier: "core",
      itemKind: "task",
      preparationKind: "task",
      bag: "none",
      bulk: "small",
    },
  ),
  templateItem(
    "general-partner-night-entrance",
    "确认夜间入院入口",
    "partner",
    "must",
    "confirm_with_hospital",
    {
      appliesTo: { partnerPresent: true },
      note: "很多医院夜间只开急诊通道，提前踩点一次。",
      packTier: "core",
      itemKind: "task",
      preparationKind: "task",
      bag: "none",
      bulk: "small",
    },
  ),
  templateItem(
    "general-partner-parking-plan",
    "确认停车方案",
    "partner",
    "must",
    "confirm_with_hospital",
    {
      appliesTo: { partnerPresent: true },
      note: "看好停车场入口和收费标准，顺便确认夜间是否开放。",
      packTier: "core",
      itemKind: "task",
      preparationKind: "task",
      bag: "car",
      bulk: "small",
    },
  ),
  templateItem(
    "general-partner-doc-folder",
    "确认证件包位置",
    "partner",
    "must",
    "pack_now",
    {
      appliesTo: { partnerPresent: true },
      note: "证件包放在固定位置，全家都知道在哪儿。",
      packTier: "core",
      itemKind: "task",
      preparationKind: "task",
      bag: "documents_folder",
      bulk: "small",
    },
  ),
  templateItem(
    "general-partner-payment",
    "确认支付方式和住院押金",
    "partner",
    "must",
    "confirm_with_hospital",
    {
      note: "支付方式、住院押金和医保结算属于入院确认事项，不算待产包物品。若医院明确要求实体银行卡或现金，再作为自定义物品加入证件包。",
      appliesTo: { partnerPresent: true },
      packTier: "core",
      itemKind: "task",
      preparationKind: "task",
      bag: "none",
      bulk: "small",
    },
  ),
  templateItem(
    "general-partner-car-seat",
    "确认安全座椅安装",
    "partner",
    "must",
    "pack_now",
    {
      appliesTo: { partnerPresent: true },
      note: "孕 37 周前反向安装到后排，提前练一次拆装。",
      packTier: "core",
      itemKind: "task",
      preparationKind: "install_or_place",
      bag: "car",
      bulk: "large",
    },
  ),
  templateItem(
    "general-partner-family-notice",
    "临出门通知家人/紧急联系人",
    "partner",
    "recommended",
    "grab_before_leaving",
    {
      appliesTo: { partnerPresent: true },
      note: "出发时发一条消息：去哪家医院、走哪个门、谁在场。",
      packTier: "core",
      itemKind: "task",
      preparationKind: "task",
      bag: "last_minute",
      bulk: "small",
    },
  ),
  templateItem(
    "general-partner-id",
    "陪产人身份证件",
    "partner",
    "must",
    "grab_before_leaving",
    {
      appliesTo: { partnerPresent: true },
      note: "原件随身带，部分医院陪产登记要核对。",
      packTier: "core",
      itemKind: "item",
      bag: "dad_backpack",
      bulk: "small",
    },
  ),
  templateItem(
    "general-partner-charger",
    "手机充电器",
    "partner",
    "must",
    "pack_now",
    {
      appliesTo: { partnerPresent: true },
      quantity: "1 套",
      note: "带 2 米长线，病房插座常离床头远。",
      packTier: "core",
      itemKind: "item",
      bag: "dad_backpack",
      bulk: "small",
    },
  ),
  templateItem("general-partner-water-snacks", "水和零食", "partner", "recommended", "pack_now", {
    appliesTo: { partnerPresent: true },
    note: "陪产是体力活，备点巧克力和电解质水。",
    packTier: "core",
    itemKind: "item",
    bag: "dad_backpack",
    bulk: "medium",
  }),
  templateItem(
    "general-partner-clothes",
    "换洗衣物 1 套，如需过夜",
    "partner",
    "recommended",
    "wash_before_pack",
    {
      appliesTo: { partnerPresent: true },
      note: "陪产过夜用，选方便穿脱的。",
      packTier: "core",
      itemKind: "item",
      bag: "dad_backpack",
      bulk: "medium",
    },
  ),
  templateItem(
    "general-partner-toiletries",
    "洗漱用品，如需过夜",
    "partner",
    "recommended",
    "pack_now",
    {
      appliesTo: { partnerPresent: true },
      note: "旅行装牙刷牙膏毛巾各一，按是否过夜增减。",
      packTier: "core",
      itemKind: "item",
      bag: "dad_backpack",
      bulk: "small",
    },
  ),
  templateItem(
    "general-partner-glasses",
    "眼镜 / 隐形眼镜用品",
    "partner",
    "optional",
    "grab_before_leaving",
    {
      appliesTo: { partnerPresent: true },
      note: "熬夜陪产建议戴框架眼镜。",
      packTier: "optional",
      itemKind: "item",
      bag: "dad_backpack",
      bulk: "small",
    },
  ),
  templateItem(
    "general-partner-medicine-list",
    "个人常用药清单 / 按需确认",
    "partner",
    "optional",
    "grab_before_leaving",
    {
      note: "如有长期用药，按个人情况提前确认。",
      appliesTo: { partnerPresent: true },
      packTier: "optional",
      itemKind: "task",
      bag: "dad_backpack",
      bulk: "small",
    },
  ),
  templateItem(
    "general-partner-bedding",
    "陪护被褥 / 折叠床",
    "partner",
    "optional",
    "pack_now",
    {
      appliesTo: { partnerPresent: true },
      quantity: "1 套",
      note: "多数医院不提供陪护被褥，先确认病房是否允许放折叠床。",
      packTier: "optional",
      itemKind: "item",
      preparationKind: "pack_existing",
      bag: "car",
      bulk: "large",
    },
  ),

  templateItem(
    "general-going-home-mom-clothes",
    "妈妈出院衣物",
    "going_home",
    "must",
    "wash_before_pack",
    {
      note: "按出院季节准备，腹部宽松不压迫。",
      packTier: "core",
      itemKind: "item",
      bag: "mom_bag",
      bulk: "large",
    },
  ),
  templateItem(
    "general-going-home-baby-clothes",
    "宝宝出院衣物",
    "going_home",
    "must",
    "wash_before_pack",
    {
      note: "出院当天穿，提前从宝宝包里拿出来备好。",
      packTier: "core",
      itemKind: "item",
      bag: "baby_bag",
      bulk: "medium",
    },
  ),
  templateItem("general-going-home-blanket", "包被 / 小毯子", "going_home", "must", "wash_before_pack", {
    note: "出院路上裹宝宝用，按天气选厚度。",
    packTier: "core",
    itemKind: "item",
    bag: "baby_bag",
    bulk: "large",
  }),
  templateItem(
    "general-going-home-transport",
    "返家交通安排",
    "going_home",
    "must",
    "confirm_with_hospital",
    {
      note: "提前约好车，确认能装安全座椅，堵车时段多留余量。",
      packTier: "core",
      itemKind: "task",
      preparationKind: "install_or_place",
      bag: "car",
      bulk: "small",
    },
  ),
  templateItem(
    "general-going-home-car-seat",
    "安全座椅确认",
    "going_home",
    "must",
    "pack_now",
    {
      note: "宝宝第一次坐车就必须用，反向安装，出院前再检查一次卡扣。",
      packTier: "core",
      itemKind: "task",
      preparationKind: "install_or_place",
      bag: "car",
      bulk: "large",
    },
  ),

  templateItem(
    "general-question-pads",
    "医院是否提供产褥垫？",
    "hospital_questions",
    "must",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-diapers",
    "医院是否提供宝宝尿不湿？",
    "hospital_questions",
    "must",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-baby-clothes",
    "医院是否提供宝宝衣物？",
    "hospital_questions",
    "must",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-partner",
    "医院是否允许陪产？",
    "hospital_questions",
    "must",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-partner-id",
    "陪产人是否需要身份证件或其他核验？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-deposit",
    "住院押金和医保结算方式是否已确认？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-entrance",
    "入院从哪个门进入？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-night-route",
    "夜间入院入口和急诊入院路线是否已确认？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-parking",
    "停车是否方便？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-phone",
    "产科 / 住院处联系电话是否已保存？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-bed",
    "是否需要提前预约床位或办理住院手续？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-not-allowed",
    "医院是否有不建议携带的物品？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-energy-food",
    "产房是否允许带补能食品/饮料？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-baby-hospital-clothes",
    "宝宝住院衣物是否需要自带？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-tableware",
    "是否需要自带餐具/饭盒/筷勺？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-breast-pump",
    "吸奶器是否需要带？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    {
      appliesTo: { breastfeeding: true },
      removable: false,
      packTier: "confirm",
      itemKind: "question",
      bag: "none",
    },
  ),
  templateItem(
    "general-question-birth-certificate",
    "出生医学证明办理需要哪些材料？父母双方身份证、结婚证、户口本是否需要？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-sterile-pack",
    "医院是否要求购买本院无菌待产包？",
    "hospital_questions",
    "must",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-formula-policy",
    "医院对奶粉、奶瓶的政策是什么？",
    "hospital_questions",
    "must",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-companion-bed",
    "陪产家属的陪护床 / 被褥是否提供？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    {
      appliesTo: { partnerPresent: true },
      removable: false,
      packTier: "confirm",
      itemKind: "question",
      preparationKind: "question",
      bag: "none",
    },
  ),
  templateItem(
    "general-question-epidural",
    "无痛分娩是否需要提前预约？麻醉师是否 24 小时在岗？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-ward-type",
    "病房类型有哪些？单人间如何预约？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-basin-monitor-belt",
    "是否需要自带便盆 / 胎心监护带？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-hot-water",
    "病房是否有热水 / 微波炉可用？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),
  templateItem(
    "general-question-breastfeeding-support",
    "医院是否提供母乳喂养指导 / 通乳服务？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    {
      appliesTo: { breastfeeding: true },
      removable: false,
      packTier: "confirm",
      itemKind: "question",
      preparationKind: "question",
      bag: "none",
    },
  ),
  templateItem(
    "general-question-belly-wrap",
    "收腹带是否需要自备、产后何时可以用？",
    "hospital_questions",
    "recommended",
    "confirm_with_hospital",
    { removable: false, packTier: "confirm", itemKind: "question", preparationKind: "question", bag: "none" },
  ),

  templateItem("general-last-id", "身份证件", "last_minute", "must", "grab_before_leaving", {
    removable: false,
    packTier: "core",
    itemKind: "task",
    preparationKind: "last_minute",
    bag: "last_minute",
    bulk: "small",
  }),
  templateItem(
    "general-last-medical-card",
    "医保卡 / 社保卡",
    "last_minute",
    "must",
    "grab_before_leaving",
    {
      removable: false,
      packTier: "core",
      itemKind: "task",
      preparationKind: "last_minute",
      bag: "last_minute",
      bulk: "small",
    },
  ),
  templateItem(
    "general-last-maternal-book",
    "北京市母子健康手册或本地区孕产资料",
    "last_minute",
    "must",
    "grab_before_leaving",
    {
      removable: false,
      packTier: "core",
      itemKind: "task",
      preparationKind: "last_minute",
      bag: "last_minute",
      bulk: "small",
    },
  ),
  templateItem(
    "general-last-prenatal-records",
    "产检资料",
    "last_minute",
    "must",
    "grab_before_leaving",
    {
      removable: false,
      packTier: "core",
      itemKind: "task",
      preparationKind: "last_minute",
      bag: "last_minute",
      bulk: "medium",
    },
  ),
  templateItem("general-last-phone", "手机", "last_minute", "must", "grab_before_leaving", {
    removable: false,
    packTier: "core",
    itemKind: "task",
    preparationKind: "last_minute",
    bag: "last_minute",
    bulk: "small",
  }),
  templateItem("general-last-charger", "充电器", "last_minute", "must", "grab_before_leaving", {
    removable: false,
    packTier: "core",
    itemKind: "task",
    preparationKind: "last_minute",
    bag: "last_minute",
    bulk: "small",
  }),
  templateItem(
    "general-last-mom-bag",
    "妈妈包放到固定位置",
    "last_minute",
    "must",
    "grab_before_leaving",
    {
      removable: false,
      packTier: "core",
      itemKind: "task",
      preparationKind: "last_minute",
      bag: "last_minute",
      bulk: "large",
    },
  ),
  templateItem(
    "general-last-baby-bag",
    "宝宝包放到固定位置",
    "last_minute",
    "must",
    "grab_before_leaving",
    {
      removable: false,
      packTier: "core",
      itemKind: "task",
      preparationKind: "last_minute",
      bag: "last_minute",
      bulk: "large",
    },
  ),
  templateItem(
    "general-last-medicine-list",
    "常用药清单 / 医生确认用药",
    "last_minute",
    "must",
    "grab_before_leaving",
    {
      note: "如有长期用药，请提前向医生或护士确认携带和使用方式。",
      removable: false,
      packTier: "core",
      itemKind: "task",
      preparationKind: "last_minute",
      bag: "last_minute",
      bulk: "small",
    },
  ),
  templateItem(
    "general-last-glasses",
    "眼镜 / 隐形眼镜",
    "last_minute",
    "must",
    "grab_before_leaving",
    {
      removable: false,
      packTier: "core",
      itemKind: "task",
      preparationKind: "last_minute",
      bag: "last_minute",
      bulk: "small",
    },
  ),
  templateItem(
    "general-last-payment",
    "支付 / 押金确认",
    "last_minute",
    "must",
    "grab_before_leaving",
    {
      removable: false,
      packTier: "core",
      itemKind: "task",
      preparationKind: "task",
      bag: "none",
      bulk: "small",
    },
  ),
  templateItem(
    "general-last-car-seat",
    "安全座椅确认",
    "last_minute",
    "must",
    "grab_before_leaving",
    {
      removable: false,
      packTier: "core",
      itemKind: "task",
      preparationKind: "install_or_place",
      bag: "car",
      bulk: "large",
    },
  ),
];