import type { TemplateChecklistItem } from "@/lib/types";

// 数据维护说明：
// 下面每个 section 对应一个分类，数组里每行是一个条目，列依次为：
// [id 后缀（自动补 "general-" 前缀）, 名称, 优先级, 时机, 数量, 备注,
//  打包层级, 条目类型, 筹备方式, 收纳包, 体积, 可移除]
// 数量 / 筹备方式两列填空字符串 "" 表示该字段不存在；可移除列省略时表示 true。
type RowArgs = [
  id: string,
  name: string,
  priority: TemplateChecklistItem["priority"],
  timing: TemplateChecklistItem["timing"],
  quantity: string,
  note: string,
  packTier: NonNullable<TemplateChecklistItem["packTier"]>,
  itemKind: NonNullable<TemplateChecklistItem["itemKind"]>,
  preparationKind: NonNullable<TemplateChecklistItem["preparationKind"]> | "",
  bag: NonNullable<TemplateChecklistItem["bag"]>,
  bulk: NonNullable<TemplateChecklistItem["bulk"]>,
  removable?: boolean,
];

function section(
  category: TemplateChecklistItem["category"],
  rows: RowArgs[],
): TemplateChecklistItem[] {
  return rows.map(
    ([
      id,
      name,
      priority,
      timing,
      quantity,
      note,
      packTier,
      itemKind,
      preparationKind,
      bag,
      bulk,
      removable = true,
    ]) => ({
      id: `general-${id}`,
      name,
      category,
      priority,
      source: "general",
      sourceLabel: "通用模板",
      editable: true,
      removable,
      timing,
      ...(quantity ? { quantity } : {}),
      note,
      packTier,
      itemKind,
      ...(preparationKind ? { preparationKind } : {}),
      bag,
      bulk,
    }),
  );
}

export const generalTemplate: TemplateChecklistItem[] = [
  ...section("documents", [
    ["doc-id", "身份证件", "must", "pack_now", "父母双方原件各 1 份，复印件按医院要求", "用于入院登记及后续材料核验；建议父母双方原件分别装袋，复印件数量先向医院确认。", "core", "item", "document", "documents_folder", "small", false],
    ["doc-health-book", "母子健康手册", "must", "pack_now", "原件 1 本", "用于入院时核对孕产保健记录；北京市通常携带母子健康手册原件，其他地区按当地手册名称准备。", "core", "item", "document", "documents_folder", "small", false],
    ["doc-medical-card", "医保卡 / 社保卡", "must", "pack_now", "实体卡 1 张 + 可正常打开的电子凭证", "用于就诊与医保结算；建议携带本人实体卡，并在出发前确认医保电子凭证可以正常打开。", "core", "item", "document", "documents_folder", "small", false],
    ["doc-prenatal-records", "产检资料", "must", "pack_now", "门诊病历、影像、化验及会诊资料原件 1 套", "用于医护人员了解孕期检查记录；建议把产科门诊病历、影像、化验单和妊娠相关会诊资料按日期整理。", "core", "item", "document", "documents_folder", "medium", false],
    ["doc-admission", "入院资料", "must", "pack_now", "医院已开具材料 1 套", "用于办理住院手续；建议把住院证、入院通知单等已开具材料与产检资料放在同一文件袋。", "core", "item", "document", "documents_folder", "small", false],
    ["doc-birth-plan", "分娩偏好卡 / 出生计划", "recommended", "pack_now", "打印 1-2 份", "用于快速说明个人偏好、过敏信息和联系人；建议控制在一页并打印一至两份，内容以现场沟通为准。", "core", "item", "document", "documents_folder", "small"],
    ["doc-cash", "少量现金", "optional", "pack_now", "约 200-500 元零钱", "用于手机支付不便或临时小额支出；建议只备少量零钱，具体金额按医院支付方式调整。", "optional", "item", "", "documents_folder", "small"],
    ["doc-marriage-cert", "结婚证", "recommended", "pack_now", "原件 1 本，复印件按当地要求", "部分地区办理相关材料时可能核验；建议先确认当地要求，再与户口本一起放入证件袋。", "core", "item", "document", "documents_folder", "small"],
    ["doc-hukou", "户口本", "recommended", "pack_now", "原件 1 本，复印件按当地要求", "部分地区办理相关材料时可能核验；建议先确认当地要求，再与结婚证一起放入证件袋。", "core", "item", "document", "documents_folder", "small"],
    ["doc-birth-registration", "生育服务单 / 生育登记凭证", "recommended", "pack_now", "纸质或电子凭证 1 份", "用于当地生育登记信息核验；各地名称和形式不同，建议保存一份可离线出示的凭证。", "core", "item", "document", "documents_folder", "small"],
    ["doc-bank-card", "银行卡", "recommended", "pack_now", "常用银行卡 1 张", "用于押金或手机支付受限时备用；建议携带一张常用卡，并提前确认额度和密码。", "core", "item", "document", "documents_folder", "small"],
  ]),
  ...section("mom_labor", [
    ["labor-phone", "手机", "must", "grab_before_leaving", "常用手机 1 部", "用于联系医院、家人和查看资料；建议出发前充足电，并把紧急联系人置顶。", "core", "item", "last_minute", "last_minute", "small", false],
    ["labor-power-bank", "充电宝", "must", "pack_now", "充满电的充电宝 1 个", "用于产房插座不便时给手机补电；装包前充满电并带好匹配短线。", "core", "item", "pack_existing", "mom_bag", "small"],
    ["labor-energy-food", "运动饮料 / 电解质饮料，按医院要求", "recommended", "confirm_beforehand", "允许携带后备 1-2 瓶小包装", "用于医护允许进食饮水时按需补充；是否能喝、何时喝以及品类限制以现场医护要求为准。", "confirm", "item", "buy_and_pack", "mom_bag", "small"],
    ["labor-snacks", "易消化小零食，按医院要求", "recommended", "confirm_beforehand", "允许携带后备 1-2 份独立小包装", "用于等待时间较长且医护允许进食时补能；优先选易开启、气味轻的小包装，禁食时不要食用。", "confirm", "item", "buy_and_pack", "mom_bag", "small"],
    ["labor-clothes", "产房换穿睡衣，按医院要求", "recommended", "confirm_beforehand", "宽松前开睡衣 1 套", "部分医院统一提供病号服，部分允许自带；先向产房确认，允许时再把一套单独放入产房包。", "confirm", "item", "wash_then_pack", "mom_bag", "medium"],
    ["labor-slippers", "防滑拖鞋（产房用）", "must", "pack_now", "易穿脱拖鞋 1 双", "用于待产期间下床活动；建议选防滑、宽松、容易穿脱的一双，产后可继续带到病房。", "core", "item", "pack_existing", "mom_bag", "medium"],
    ["labor-pads", "产褥垫（产房用），按医院要求", "recommended", "confirm_beforehand", "当前分装计划 3 包，规格按医院要求", "用于产房铺垫和护理；三包是当前分装计划，不是医院统一标准，请确认尺寸、每包片数、即时用量及院方是否提供。", "confirm", "item", "buy_and_pack", "mom_bag", "large"],
    ["labor-paper", "刀纸 / 产褥卫生纸（产房用），按医院要求", "recommended", "confirm_beforehand", "当前分装计划 2 包，规格按医院要求", "用于院方明确要求的产房护理场景；两包是当前分装计划，请确认尺寸、包装及院方是否提供。", "confirm", "item", "buy_and_pack", "mom_bag", "medium"],
    ["labor-cup", "吸管杯，或带盖水杯 + 匹配吸管", "must", "pack_now", "可单手使用的杯子 1 个", "用于不便起身时饮水；吸管杯和普通带盖杯搭配吸管二选一即可，建议选防漏、约五百至八百毫升且便于清洗的款式。", "core", "item", "pack_existing", "mom_bag", "medium"],
    ["labor-straws", "备用一次性吸管", "optional", "pack_now", "需要时带独立包装 5-10 根", "仅在水杯没有吸管或需要临时替换时携带；已有可拆洗吸管杯可不重复准备。", "optional", "item", "buy_and_pack", "mom_bag", "small"],
    ["labor-ctg-belt", "胎心监护带，按医院要求", "recommended", "confirm_beforehand", "院方要求时按通知准备", "用于医院要求自带时配合胎心监护；并非所有医院统一必带，请产检时确认数量和规格。", "confirm", "item", "buy_and_pack", "mom_bag", "small"],
    ["labor-lip-balm", "护唇膏", "must", "pack_now", "无香型小支装 1 支", "用于空调环境或长时间说话时保持唇部舒适；建议带一支无香型小包装并单独收好。", "core", "item", "pack_existing", "mom_bag", "small"],
    ["labor-cooling", "小风扇 / 喷雾瓶", "optional", "pack_now", "小风扇或喷雾瓶 1 个", "用于闷热环境下增加舒适感；建议选小型、低噪款，并先确认病区是否允许使用。", "optional", "item", "pack_existing", "mom_bag", "small"],
    ["labor-relaxation", "耳机 / 放松音频", "optional", "grab_before_leaving", "耳机 1 副，音频提前离线", "用于等待或休息时听熟悉的音频；建议准备一副已充电耳机，并提前下载离线内容。", "optional", "item", "last_minute", "last_minute", "small"],
    ["labor-tens", "TENS 镇痛仪，如已决定使用", "optional", "pack_now", "确认使用后带 1 套", "用于已与医护人员沟通确认的个人舒缓方案；建议只在允许使用时携带完整一套及匹配电源。", "optional", "item", "pack_existing", "mom_bag", "small"],
    ["labor-glasses", "眼镜 / 隐形眼镜用品，如适用", "must", "grab_before_leaving", "框架眼镜 1 副 + 眼镜盒 1 个", "用于住院期间清晰视物；建议以框架眼镜为主，并把隐形眼镜护理用品按个人需要另装。", "core", "item", "last_minute", "last_minute", "small"],
    ["labor-medicine-list", "常用药清单 / 医生确认用药", "must", "grab_before_leaving", "", "如有长期用药，请提前向医生或护士确认携带和使用方式。", "core", "task", "last_minute", "last_minute", "small"],
  ]),
  ...section("mom_postpartum", [
    ["postpartum-yuezi-clothes", "月子服 / 前开睡衣", "must", "wash_before_pack", "2 套", "用于病房内换洗和哺乳；建议准备两套宽松、透气、前开或有哺乳口的衣物，洗净晾干后装包。", "core", "item", "wash_then_pack", "mom_bag", "large"],
    ["postpartum-nursing-bra", "哺乳内衣", "recommended", "wash_before_pack", "2 件", "用于计划哺乳时方便穿脱和换洗；按孕晚期实际胸围选择两件可调节、无明显勒压感的款式。", "core", "item", "wash_then_pack", "mom_bag", "medium"],
    ["labor-socks", "袜子", "recommended", "wash_before_pack", "2 双", "用于病房空调环境下保暖和换洗；建议准备两双袜口宽松、透气的袜子。", "core", "item", "wash_then_pack", "mom_bag", "small"],
    ["postpartum-slippers", "防滑拖鞋（病房用）", "must", "pack_now", "1 双", "用于病房走动和洗漱；若产房拖鞋会随产妇转入病房，可共用同一双，不必重复购买。", "core", "item", "pack_existing", "mom_bag", "medium"],
    ["labor-towels", "毛巾", "recommended", "wash_before_pack", "2 条", "用于擦脸、擦身时分开使用；建议准备两条颜色不同、易晾干的小毛巾。", "core", "item", "wash_then_pack", "mom_bag", "medium"],
    ["postpartum-belly-wrap", "收腹带 / 束腹带", "optional", "pack_now", "1 条", "用于医护人员建议使用时提供适度支撑；先确认是否适合，再按孕晚期围度选择可调节款。", "core", "item", "buy_and_pack", "mom_bag", "medium"],
    ["postpartum-yuezi-hat-shoes", "月子帽", "optional", "wash_before_pack", "1 顶，按季节", "用于出院或病房内按个人习惯保暖；根据季节选择轻便透气款，并非医疗必需品。", "core", "item", "wash_then_pack", "mom_bag", "small"],
    ["postpartum-pads", "产褥垫（病房备用），按医院要求", "recommended", "confirm_beforehand", "当前分装计划 2 包，规格按医院要求", "用于病房床面铺垫和护理；两包是当前分装计划，不是医院统一标准，请确认尺寸、每包片数及院方是否提供。", "confirm", "item", "buy_and_pack", "mom_bag", "large"],
    ["postpartum-paper", "刀纸 / 产褥卫生纸（病房备用），按医院要求", "recommended", "confirm_beforehand", "当前分装计划 1 包，规格按医院要求", "用于病房内院方明确要求的护理场景；一包是当前分装计划，请确认尺寸、包装及院方是否提供。", "confirm", "item", "buy_and_pack", "mom_bag", "medium"],
    ["postpartum-sanitary-pads", "产后卫生巾", "must", "pack_now", "2 包", "用于产后恶露期按需更换；建议准备加长夜用和普通规格各一包，实际使用遵照医护建议。", "core", "item", "buy_and_pack", "mom_bag", "medium"],
    ["postpartum-pull-up-pants", "产妇安心裤 / 拉拉裤", "recommended", "pack_now", "2 包", "用于住院初期方便穿脱和更换；按孕晚期实际腰臀围选码，先确认医院是否另要求成人纸尿裤。", "core", "item", "buy_and_pack", "mom_bag", "medium"],
    ["postpartum-underwear", "一次性内裤", "must", "pack_now", "2 盒，或按住院天数 + 2 条准备", "用于住院期间便捷换洗；不同品牌每盒条数不同，至少按预计住院天数多备两条，并按孕晚期腰臀围选码。", "core", "item", "buy_and_pack", "mom_bag", "small"],
    ["postpartum-gloves", "一次性手套（普通医用）", "recommended", "confirm_beforehand", "医院或护理需要时 1 小盒", "用于病区明确要求或家属协助清洁时使用；多数日常护理并非统一必备，请先向病区确认。", "confirm", "item", "buy_and_pack", "mom_bag", "small"],
    ["postpartum-toilet-seat-covers", "一次性马桶垫（家用型）", "recommended", "pack_now", "1 包", "用于使用病房公共马桶时按个人习惯铺垫；建议选覆盖面积较大、独立或抽取方便的家用型。", "core", "item", "buy_and_pack", "mom_bag", "small"],
    ["postpartum-peri-bottle", "会阴冲洗器", "recommended", "pack_now", "1 个", "用于医院建议时清洁外阴和会阴表面；不伸入阴道，水温和使用方法按医护指导，建议选择约三百至五百毫升、弯嘴且便于清洗的瓶子。", "core", "item", "buy_and_pack", "mom_bag", "small"],
    ["labor-moon-toothbrush", "牙膏牙刷", "must", "pack_now", "旅行装牙膏和软毛牙刷各 1 个", "用于住院期间保持口腔清洁；普通软毛牙刷即可，不必专门购买所谓“月子牙刷”。", "core", "item", "pack_existing", "mom_bag", "small"],
    ["labor-toiletries", "其他洗漱用品", "recommended", "pack_now", "洁面、梳子和发圈等旅行装 1 小包", "用于病房内日常清洁和整理；牙膏牙刷已单列，这里按个人习惯装入洁面、梳子、发圈等用品。", "core", "item", "pack_existing", "mom_bag", "small"],
    ["postpartum-thermos", "保温杯", "must", "pack_now", "带盖保温杯 1 个", "用于病房内饮水；建议选防漏、易清洗且可单手开启的款式，与产房吸管杯分开装。", "core", "item", "pack_existing", "mom_bag", "medium"],
    ["postpartum-going-home-clothes", "妈妈出院衣物（装入病房包）", "must", "wash_before_pack", "1 套", "用于出院当天舒适穿着；与“返家准备”中的出院衣物复核任务对应，只需准备并装入这一套。", "core", "item", "wash_then_pack", "mom_bag", "large"],
    ["labor-tissues", "妈妈干纸巾 / 湿巾", "recommended", "pack_now", "各 1 包", "用于病房日常清洁和擦拭；建议准备纸巾和无香湿巾各一包，和宝宝用品分开放。", "core", "item", "buy_and_pack", "mom_bag", "medium"],
    ["labor-long-cable", "长充电线", "recommended", "pack_now", "约 2 米、接口匹配的线 1 条", "用于病床附近给手机充电；与产房包的充电宝分开准备，装包前检查外皮和接口。", "core", "item", "pack_existing", "mom_bag", "small"],
    ["labor-eye-mask", "眼罩", "optional", "pack_now", "遮光眼罩 1 个", "用于病房灯光较亮时休息；建议选柔软、松紧可调且便于清洗的款式。", "optional", "item", "pack_existing", "mom_bag", "small"],
    ["labor-pillow", "自用枕头，如需要", "optional", "pack_now", "枕头 1 个，按个人需要", "用于提高住院休息舒适度；如决定携带，套上易识别、可清洗的枕套。", "optional", "item", "pack_existing", "mom_bag", "large"],
    ["postpartum-metered-pads", "计量型卫生巾", "recommended", "pack_now", "医院要求时 1 小包", "用于医院有明确计量记录要求的场景；建议只在医护人员要求时购买一小包，并确认具体规格。", "optional", "item", "buy_and_pack", "mom_bag", "small"],
    ["postpartum-storage-bags", "收纳袋 / 脏衣袋", "must", "pack_now", "3-5 个", "用于分开放置干净用品、湿物和脏衣物；建议准备三至五个不同尺寸、可封口的收纳袋。", "core", "item", "pack_existing", "mom_bag", "small"],
    ["postpartum-breast-pads", "溢乳垫", "optional", "pack_now", "先备 1 小包，约 10-20 片", "用于计划哺乳时按需保持衣物干爽；建议先备十至二十片小包装，使用量稳定后再补充。", "optional", "item", "buy_and_pack", "mom_bag", "small"],
    ["postpartum-nipple-cream", "乳头膏", "optional", "pack_now", "小支装 1 支，按需", "用于计划哺乳时按个人需要进行皮肤护理；建议选成分简单的小支装，使用方式以产品说明和专业建议为准。", "optional", "item", "buy_and_pack", "mom_bag", "small"],
    ["postpartum-adult-diapers", "成人纸尿裤", "optional", "pack_now", "按需 1 小包", "用于部分医院产房或产后明确要求时；建议先向医院确认是否需要，不要求则不必携带。常见品牌：包大人。", "optional", "item", "buy_and_pack", "mom_bag", "medium"],
    ["postpartum-cold-pack", "会阴冷敷贴", "optional", "pack_now", "3-5 片", "顺产后如医护建议，可用于短时冷敷、缓解会阴肿胀不适；建议先备三至五片，使用时避免直接接触皮肤，并确认医院是否提供或允许使用。", "optional", "item", "buy_and_pack", "mom_bag", "small"],
    ["postpartum-basins", "妈妈清洁盆 / 折叠盆", "optional", "confirm_beforehand", "病区要求时 1 个", "用于病房内个人清洁；是否需要自备及能否使用折叠款以病区通知为准，并与宝宝澡盆、奶瓶专用盆区分。", "confirm", "item", "buy_and_pack", "mom_bag", "medium"],
    ["postpartum-breast-pump", "吸奶器", "recommended", "pack_now", "1 套", "用于计划哺乳且确有挤奶需要时备用；建议带一套已试装设备，电动款充好电，接触奶液的配件按说明清洁后装袋。", "core", "item", "wash_then_pack", "mom_bag", "medium"],
    ["postpartum-milk-bags", "储奶袋", "optional", "pack_now", "先备 10-20 片", "用于确有储存母乳需要时分装和标记；建议先备十至二十片小容量袋，储存方式按医院指导执行。", "optional", "item", "buy_and_pack", "mom_bag", "small"],
    ["labor-tableware", "餐具 / 饭盒筷勺", "optional", "pack_now", "1 套", "用于医院不提供餐具或家属送餐时使用；建议准备一套带盖、易清洗的饭盒和筷勺。", "optional", "item", "wash_then_pack", "mom_bag", "medium"],
  ]),
  ...section("baby", [
    ["baby-hospital-clothes", "宝宝上衣（52 码），按病区要求", "recommended", "confirm_beforehand", "当前计划 2-3 件", "用于医院要求自带时给宝宝在病房换洗；先确认院方是否提供以及何时可使用，再准备柔软、无硬饰且易穿脱的和尚服或上衣。", "confirm", "item", "wash_then_pack", "baby_bag", "medium"],
    ["baby-blanket", "包被，按医院要求", "recommended", "confirm_beforehand", "当前计划 2 件，交接数量按院方通知", "用于院方交接、病房包裹或出院途中按需保暖；部分医院提供或现场售卖，请确认需要交给产房的数量和时间。", "confirm", "item", "wash_then_pack", "baby_bag", "large"],
    ["baby-sheet", "薄棉包单，按医院要求", "recommended", "confirm_beforehand", "院方要求时准备 1-2 条", "部分非妇产专科医院或病区可能要求自带薄棉包单；没有统一规则，请按分娩医院的入院通知准备。", "confirm", "item", "wash_then_pack", "baby_bag", "medium"],
    ["baby-bath-basin", "宝宝澡盆，按医院要求", "recommended", "confirm_beforehand", "病区要求时 1 个", "北京妇产医院官网健康宣教文章将长椭圆形澡盆列为参考用品；普通病房是否自备、尺寸及能否使用折叠款，以当前病区通知为准。", "confirm", "item", "buy_and_pack", "baby_bag", "large"],
    ["baby-socks", "宝宝袜子", "recommended", "wash_before_pack", "1-2 双", "用于病房或出院途中按季节保暖；准备袜口宽松、无线头明显残留的袜子。", "core", "item", "wash_then_pack", "baby_bag", "small"],
    ["baby-hat", "宝宝胎帽，按季节 / 院方要求", "recommended", "confirm_beforehand", "需要时 1 顶", "用于院方交接、抱出或出院途中按天气保暖；选择无硬饰、松紧合适的一顶，并确认院方是否提供。", "confirm", "item", "wash_then_pack", "baby_bag", "small"],
    ["baby-cover-blanket", "宝宝盖毯", "optional", "wash_before_pack", "按季节准备 1 条", "仅用于宝宝清醒且有人看护时、抱出或出院途中按需保暖；宝宝睡眠区域不要放松软盖毯，具体安排遵照病区安全睡眠指导。", "core", "item", "wash_then_pack", "baby_bag", "large"],
    ["baby-towels", "宝宝小方巾", "recommended", "wash_before_pack", "3-5 条", "用于喂奶垫巾、拍嗝和日常擦拭；准备颜色或图案易区分、洗后易干的小方巾。", "core", "item", "wash_then_pack", "baby_bag", "small"],
    ["baby-bath-towels", "纱布浴巾（病房用）", "recommended", "wash_before_pack", "2 条", "用于宝宝在病房洗澡或清洁后包裹擦干；建议准备两条柔软、吸水、易晾干的纱布浴巾。", "core", "item", "wash_then_pack", "baby_bag", "medium"],
    ["baby-formula", "新生儿配方奶粉，按喂养方案", "optional", "confirm_beforehand", "确认需要后带小包装 1 份", "计划母乳喂养时，除医学指征外不自行补充配方奶；是否携带和补喂以院方及医护人员确认的喂养方案为准。", "confirm", "item", "buy_and_pack", "baby_bag", "medium"],
    ["baby-formula-bottle", "奶瓶 + 匹配的新生儿流量奶嘴", "optional", "confirm_beforehand", "确认瓶喂后准备奶瓶 1 个", "按医院和实际喂养需要准备；奶嘴流量和型号应结合品牌说明、宝宝胎龄与喂养能力，并听从医护指导，不同品牌规格通常不通用。", "confirm", "item", "buy_and_pack", "baby_bag", "medium"],
    ["baby-bottle-cleanser", "奶瓶清洗剂", "optional", "confirm_beforehand", "确认使用奶瓶后带小瓶 1 瓶", "用于清洗接触奶液的奶瓶配件；只有实际瓶喂时才需带，选择易冲洗的小规格并按产品说明使用。", "confirm", "item", "buy_and_pack", "baby_bag", "small"],
    ["baby-bottle-brush", "奶瓶刷", "optional", "confirm_beforehand", "确认使用奶瓶后带 1 套", "用于清洁奶瓶及奶嘴；准备尺寸匹配、奶瓶与奶嘴可分刷的一套，用后清洗并充分晾干。", "confirm", "item", "buy_and_pack", "baby_bag", "small"],
    ["baby-bottle-basin", "奶瓶专用小盆（清洗 / 烫洗）", "recommended", "confirm_beforehand", "按医院设施及瓶喂需要准备 1 个", "用于把喂养用品与水槽、宝宝澡盆分开清洗或按院方要求烫洗；能否接触热水应查看盆和奶瓶的材质说明。若需煮沸消毒，应使用适合的锅具或设备，普通塑料盆不能代替。", "confirm", "item", "buy_and_pack", "baby_bag", "medium"],
    ["baby-diapers", "尿不湿", "must", "pack_now", "NB 码先备 1 小包，约 24-36 片", "用于住院期间按需更换；建议 NB 码先买一小包，出生后再按宝宝体重、腰围和贴合情况决定是否换码。", "core", "item", "buy_and_pack", "baby_bag", "medium"],
    ["baby-cotton-tissues", "棉柔巾", "must", "pack_now", "2 包", "用于蘸温水后进行日常清洁；建议选择无香、柔软的小包装，并与成人清洁用品分开放。", "core", "item", "buy_and_pack", "baby_bag", "medium"],
    ["baby-cloud-tissues", "云柔巾", "recommended", "pack_now", "2 包", "用于宝宝口鼻周围或日常轻柔擦拭；建议选择无香、掉絮少的产品。", "core", "item", "buy_and_pack", "baby_bag", "medium"],
    ["baby-wipes", "婴儿干纸巾 / 湿巾", "must", "pack_now", "各 1 包", "用于换洗时擦拭皮肤或清理台面；选择无香型小包装，并先确认医院是否提供。", "core", "item", "buy_and_pack", "baby_bag", "medium"],
    ["baby-diaper-cream", "护臀膏", "optional", "pack_now", "小支装 1 支，按需", "用于换洗后按个人护理方案隔离潮湿；建议只带一支成分简单的小包装，使用按说明或专业建议进行。", "core", "item", "buy_and_pack", "baby_bag", "small"],
    ["baby-changing-pads", "一次性隔尿垫", "optional", "pack_now", "10-20 片", "用于换尿布时保护床面或护理台；建议准备十至二十片约四十五乘六十厘米的小包装。", "core", "item", "buy_and_pack", "baby_bag", "medium"],
    ["baby-touch-oil", "婴儿抚触油", "optional", "pack_now", "小瓶装 1 瓶，按需", "用于医护指导或家庭护理方案中的抚触；选择成分简单的小瓶装，使用前按说明少量尝试。", "core", "item", "buy_and_pack", "baby_bag", "small"],
    ["baby-lotion", "婴儿身体乳（病房小包装）", "optional", "pack_now", "无香型小瓶 1 瓶，按需", "用于病房内皮肤干燥时按需保湿；选择无香、成分简单的小规格，使用前按说明少量尝试。", "core", "item", "buy_and_pack", "baby_bag", "small"],
    ["baby-face-cream", "婴儿面霜（病房小包装）", "optional", "pack_now", "小盒装 1 盒，按需", "用于病房内面部皮肤干燥时按需保湿；选择无香、成分简单的小包装，不必与身体乳重复厚涂。", "core", "item", "buy_and_pack", "baby_bag", "small"],
    ["baby-nail-clipper", "宝宝指甲剪", "optional", "pack_now", "1 个", "用于确有修剪需要时整理指甲边缘；建议准备一个圆头、握持稳定且带保护盖的小剪具。", "hidden", "item", "", "baby_bag", "small"],
    ["baby-navel-care", "护脐贴 + 碘伏棉签，按医院要求", "recommended", "confirm_beforehand", "医院明确要求时各 1 小份", "用于医院明确要求的脐部护理用品准备；先询问是否需要及具体规格，不自行增加处理步骤。", "confirm", "item", "buy_and_pack", "baby_bag", "small"],
    ["baby-cotton-swabs", "婴儿细轴棉签", "optional", "pack_now", "1 盒", "用于皮肤表面或耳廓外侧的轻柔清洁；建议选细轴纸杆小包装，并避免伸入鼻腔或耳道。", "optional", "item", "buy_and_pack", "baby_bag", "small"],
    ["baby-laundry", "婴儿洗衣液 / 洗衣皂 + 小衣架，按病区要求", "optional", "confirm_beforehand", "病区允许时带小规格 1 份 + 小衣架 1 套", "仅在病区允许手洗并晾晒宝宝小件衣物时使用；选择小规格、易漂洗产品，并先确认晾晒条件。", "confirm", "item", "buy_and_pack", "baby_bag", "medium"],
    ["baby-home-clothes", "宝宝出院衣物（装入病房包）", "must", "wash_before_pack", "1 套 + 备用 1 套", "用于宝宝出院当天穿着和临时替换；与“返家准备”中的出院衣物是同一套，不必重复购买或装包。", "core", "item", "wash_then_pack", "baby_bag", "medium"],
  ]),
  ...section("confinement_mom", [
    ["confinement-mom-yuezi-clothes", "月子服", "recommended", "prepare_now", "纯棉哺乳款 2-3 套", "用于月子期间换洗；产后出汗多、易溢奶，建议选纯棉透气、前开扣或带哺乳口的款式，到手先清洗。常见品牌：嫚熙、babycare。", "core", "item", "buy_for_home", "none", "medium"],
    ["confinement-mom-pads-stock", "夜用卫生巾 / 安心裤（家中囤货）", "recommended", "prepare_now", "420 毫米夜用 2-3 包或安心裤 1-2 包", "用于月子期间持续约四至六周的恶露；建议前期用加长夜用或安心裤，量变少后换普通款。常见品牌：高洁丝、苏菲、她研社。", "core", "item", "buy_for_home", "none", "medium"],
    ["confinement-mom-underwear-stock", "一次性内裤（家中补充）", "recommended", "prepare_now", "按需补充 10-20 条", "用于恶露期换洗频繁时直接更换；住院带的数量不够时提前补足。常见品牌：嫚熙、十月结晶。", "optional", "item", "buy_for_home", "none", "small"],
    ["confinement-mom-nursing-pads-stock", "防溢乳垫（家中补充）", "optional", "prepare_now", "先备 1 小盒，用量稳定后再补", "用于母乳量稳定前防止溢奶弄脏衣物；每个人的溢奶量差异很大，先接着住院小包少量试用，确认材质合适和实际用量后再补，不必提前囤整箱。", "optional", "item", "buy_for_home", "none", "small"],
    ["confinement-mom-milk-bags-stock", "储奶袋（家中补充）", "optional", "prepare_now", "先备 10-20 片，确认有存奶需求后再补", "用于确有存奶需求时分装冷冻；先用十至二十片小容量袋，确认泌乳、喂养和存奶节奏后再补，避免在尚未使用前大量囤货。", "optional", "item", "buy_for_home", "none", "small"],
    ["confinement-mom-pumping-bra", "免手扶吸奶文胸", "optional", "prepare_now", "确认使用双边吸奶器后备 1 件", "用于双边吸奶时固定喇叭罩、腾出双手；先确认吸奶器类型和实际使用频率，可调节或能利用现有哺乳内衣的方案更省，确定需要后再买。", "optional", "item", "buy_for_home", "none", "small"],
    ["confinement-mom-nursing-pillow", "哺乳枕", "optional", "prepare_now", "1 个", "用于喂奶时垫高手臂、减轻腰背负担；非必备，也可先用孕妇枕或靠垫代替。常见品牌：嫚熙、佳韵宝。", "optional", "item", "buy_for_home", "none", "large"],
    ["confinement-mom-diaper-bag", "妈咪包", "optional", "prepare_now", "1 个", "用于带宝宝体检、打疫苗时分区收纳出门用品；不着急，出生后按需要再买。常见品牌：嫚熙、babycare。", "optional", "item", "buy_for_home", "none", "medium"],
  ]),
  ...section("confinement_baby", [
    ["confinement-baby-diapers-stock", "纸尿裤囤货（NB + S 码）", "must", "prepare_now", "NB 试用装或小包 1-2 包，S 码暂不多囤", "用于月子里高频更换；不同品牌版型、宝宝体重和皮肤适应情况差异很大，先备试用装或一两小包，出生后确认不漏尿、不勒腿再按码数补货。", "core", "item", "buy_for_home", "none", "large"],
    ["confinement-baby-bottles", "奶瓶", "recommended", "prepare_now", "160 毫升 + 240 毫升各 1 个，配 SS/S 码奶嘴", "用于母乳不足或瓶喂时；建议先各备一个，奶嘴一至两个月更换一次。常见品牌：贝亲、hegen、世喜、布朗博士。", "core", "item", "buy_for_home", "none", "small"],
    ["confinement-baby-formula", "一段奶粉", "recommended", "prepare_now", "一段小罐（约 400 克）1 罐", "用于家庭确定需要配方奶时备用；只备一罐小包装，不提前囤多罐，喂养方案优先结合宝宝情况和专业建议，未使用时保持密封并留意有效期。", "core", "item", "buy_for_home", "none", "medium"],
    ["confinement-baby-kettle", "恒温水壶 / 调奶器", "recommended", "prepare_now", "1 个", "仅在确定配方奶喂养后按需准备；冲调应严格按产品标签和医护指导，不要用恒温壶的固定设定温度代替安全冲调步骤。", "optional", "item", "buy_for_home", "none", "medium"],
    ["confinement-baby-sterilizer", "奶瓶消毒器 / 消毒柜", "recommended", "prepare_now", "1 台", "用于奶瓶奶嘴和餐具日常消毒；建议选紫外线灯珠款、约 20 升容量，后期玩具餐具也能用。常见品牌：波咯咯、大宇、小白熊。", "optional", "item", "buy_for_home", "none", "large"],
    ["confinement-baby-bottle-warmer", "温奶器", "optional", "prepare_now", "1 个", "用于瓶喂母乳时均匀温奶；使用频率不确定，需要时再买也来得及。常见品牌：小白熊、波咯咯。", "optional", "item", "buy_for_home", "none", "small"],
    ["confinement-baby-pacifier", "安抚奶嘴", "optional", "prepare_now", "1-2 个", "用于宝宝需要安抚时备用；非必备，注意按月龄选型号并勤清洗。常见品牌：新安怡、世喜。", "optional", "item", "buy_for_home", "none", "small"],
    ["confinement-baby-wash", "洗发沐浴二合一", "recommended", "prepare_now", "按压式 1 瓶", "用于给宝宝洗澡；新生儿每周用一至两次即可，建议选温和无泪配方的按压款。常见品牌：艾惟诺、施巴。", "core", "item", "buy_for_home", "none", "small"],
    ["confinement-baby-face-cream", "婴儿面霜", "recommended", "prepare_now", "1 瓶", "用于干燥季节面部保湿；建议先小面积试用，湿疹宝宝更要坚持厚涂保湿。常见品牌：妙思乐、松达、顺峰宝宝。", "core", "item", "buy_for_home", "none", "small"],
    ["confinement-baby-body-lotion", "婴儿身体乳", "recommended", "prepare_now", "1 瓶", "用于洗澡后全身薄涂保湿；大罐装耐用，全家也能一起用。常见品牌：丝塔芙大白罐、艾惟诺、松达。", "optional", "item", "buy_for_home", "none", "small"],
    ["confinement-baby-peach-water", "桃子水（液体爽身粉）", "optional", "prepare_now", "1 瓶", "用于夏季预防痱子和淹脖子；建议选液体款不用粉状，其他季节可不买。常见品牌：宇津、chuchu、贝亲。", "optional", "item", "buy_for_home", "none", "small"],
    ["confinement-baby-bath-towels", "纱布浴巾", "recommended", "prepare_now", "六层纱布 2-3 条", "用于洗澡后包裹擦干；夏天还能当包被或小盖毯，建议多备一条换洗。常见品牌：全棉时代、嫚熙。", "core", "item", "buy_for_home", "none", "medium"],
    ["confinement-baby-bibs", "口水巾", "recommended", "prepare_now", "4-6 条", "用于拍嗝垫肩、接吐奶和擦口水；消耗量大，建议多备几轮换。常见品牌：全棉时代、嫚熙。", "core", "item", "buy_for_home", "none", "small"],
    ["confinement-baby-bathtub", "折叠洗澡盆 + 浴网", "recommended", "prepare_now", "1 套", "用于在家给宝宝洗澡；建议选可折叠款好收纳，浴网比浴垫更不易发霉。常见品牌：蒂爱、嫚熙。", "optional", "item", "buy_for_home", "none", "large"],
    ["confinement-baby-bath-thermometer", "水温计", "recommended", "prepare_now", "1 个", "用于洗澡前测水温；建议控制在 36-37℃、不超过 40℃，冬天或感冒时可稍高。常见品牌：嫚熙。", "optional", "item", "buy_for_home", "none", "small"],
    ["confinement-baby-soft-tissues", "云柔巾 + 棉柔巾囤货", "recommended", "prepare_now", "各 1 提，按消耗补", "用于擦脸擦口水和打湿洗屁屁；消耗量大可以多囤，棉柔巾建议选全棉材质。常见品牌：可心柔、全棉时代、德佑。", "core", "item", "buy_for_home", "none", "medium"],
    ["confinement-baby-changing-pads-stock", "一次性隔尿垫囤货", "recommended", "prepare_now", "2 包，约 160 片", "用于换尿布、晾屁屁时垫台面；妈妈用剩的产褥垫也能替代，可按消耗慢慢补。常见品牌：德佑。", "optional", "item", "buy_for_home", "none", "medium"],
    ["confinement-baby-washable-pads", "可水洗隔尿垫", "optional", "prepare_now", "2 条，买大不买小", "用于宝宝大一点后垫床、垫尿布台反复使用；和一次性款搭配更省。常见品牌：littletiny、嫚熙、诺绵。", "optional", "item", "buy_for_home", "none", "medium"],
    ["confinement-baby-laundry-detergent", "婴儿洗衣液", "recommended", "prepare_now", "1-2 瓶", "用于宝宝衣物和口水巾天天清洗；建议选无荧光剂、温和配方。常见品牌：保宁、英氏、babycare。", "core", "item", "buy_for_home", "none", "medium"],
    ["confinement-baby-hangers", "宝宝小衣架", "recommended", "prepare_now", "20-30 个", "用于晾晒宝宝小件衣物；可伸缩款能挂成一串，节省空间。常见品牌：蒂爱。", "optional", "item", "buy_for_home", "none", "small"],
    ["confinement-baby-bodysuit", "半背衣 / 包屁衣", "recommended", "prepare_now", "52 码 2 件", "用于月子期间日常穿着、方便换尿布；建议选纯棉 A 类，到手先清洗。常见品牌：乖奇熊、全棉时代、aqpa。", "core", "item", "buy_for_home", "none", "medium"],
    ["confinement-baby-rompers", "宝宝连体衣囤货", "recommended", "prepare_now", "52、59 码各 2 套", "用于宝宝出生后换洗；宝宝长得快，建议先备两个码，出生后再追加。常见品牌：乖奇熊、全棉时代、aqpa。", "core", "item", "buy_for_home", "none", "medium"],
    ["confinement-baby-sleep-sack", "防惊跳睡袋", "optional", "prepare_now", "1-2 件", "用于小月龄睡觉时减少惊跳反射；投降式更贴合，也可先用包被替代。常见品牌：lovetodream、嫚熙、贝肽斯。", "optional", "item", "buy_for_home", "none", "medium"],
    ["confinement-baby-belly-band", "宝宝肚围", "optional", "prepare_now", "2 件", "用于换尿布、洗澡时护住肚子不受凉；选纯棉弹性款即可。常见品牌：嫚熙、童泰。", "optional", "item", "buy_for_home", "none", "small"],
    ["confinement-baby-thermometer", "耳温枪 / 体温计", "recommended", "prepare_now", "1 个", "用于宝宝发热时快速测温；耳温枪几秒出数，也可先备电子腋温计。常见品牌：博朗。", "core", "item", "buy_for_home", "none", "small"],
    ["confinement-baby-nasal-care", "婴儿生理盐水 + 手动吸鼻器", "optional", "prepare_now", "无药物生理盐水 1 小瓶 + 手动吸鼻器 1 个", "用于鼻塞时先滴入不含药物的生理盐水、再按需轻柔吸出分泌物；不把吸头深入鼻腔，也不自行加入减充血药，持续呼吸困难应及时就医。", "optional", "item", "buy_for_home", "none", "small"],
    ["confinement-baby-medicine-syringe", "毫升刻度口服喂药器", "recommended", "prepare_now", "1 支，按需使用", "用于需要口服药物时按毫升准确量取；只按药品标签或医护人员给出的剂量使用，不用家用汤匙估量，每次使用后按产品说明清洁晾干。", "optional", "item", "buy_for_home", "none", "small"],
    ["confinement-baby-vitamin-ad", "维生素 AD / D3", "must", "prepare_now", "1 盒", "用于出生约 15 天后每天补充一滴，直接滴入嘴里；具体选 AD 还是 D3 遵医嘱。", "core", "item", "buy_for_home", "none", "small"],
    ["confinement-baby-zinc-oxide", "氧化锌软膏", "recommended", "prepare_now", "1 罐", "用于红屁屁时加强隔离防护；破皮或持续不见好请就医，日常护理仍用护臀膏。", "optional", "item", "buy_for_home", "none", "small"],
    ["confinement-baby-calamine", "炉甘石洗剂", "optional", "prepare_now", "1 瓶", "用于痱子、湿疹止痒；皮肤破溃处不要用，用药前先咨询医生。", "optional", "item", "buy_for_home", "none", "small"],
    ["confinement-baby-black-white-cards", "黑白卡", "optional", "prepare_now", "1 套", "用于出生两周后练追视；每次几十秒即可，可搭配小沙锤练听力和抓握。", "optional", "item", "buy_for_home", "none", "small"],
    ["confinement-baby-night-light", "小夜灯", "optional", "prepare_now", "1 个，暖光可调", "用于半夜喂奶、换尿布时照明；建议选遥控或拍拍款，不用开大灯。", "optional", "item", "buy_for_home", "none", "small"],
    ["confinement-baby-hair-clipper", "婴儿理发器", "optional", "prepare_now", "1 套", "用于满月后在家理发；不着急买，需要时再选静音款。常见品牌：樱舒、可优比。", "optional", "item", "buy_for_home", "none", "small"],
    ["confinement-baby-crib", "婴儿床 + 床上用品", "recommended", "prepare_now", "1 套", "用于宝宝在家独立安睡；按安全睡眠要求选择结构牢固、床垫贴合的产品，二手可考虑，但要确认无缺件、无召回、无损坏，并配齐原说明书。", "core", "item", "buy_for_home", "none", "large"],
    ["confinement-baby-changing-table", "尿布台", "optional", "prepare_now", "1 个", "用于站着换尿布、做抚触，减轻弯腰；也可用床上隔尿垫代替。常见品牌：honeyseed、可优比。", "optional", "item", "buy_for_home", "none", "large"],
    ["confinement-baby-stroller", "婴儿推车", "recommended", "prepare_now", "1 辆", "用于出月子后遛娃；月子里基本用不到，可以出生后试推再买。二手可考虑，但要检查车架、刹车、折叠锁和安全带是否完整可靠。", "optional", "item", "buy_for_home", "none", "large"],
    ["confinement-baby-washer", "婴儿洗衣机", "optional", "prepare_now", "1 台", "用于宝宝衣物单独清洗；带煮洗功能更好，预算有限也可手洗。常见品牌：海信、美的。", "optional", "item", "buy_for_home", "none", "large"],
    ["confinement-baby-storage-cart", "置物小推车", "optional", "prepare_now", "1 辆", "用于把尿布、湿巾和护肤品集中收纳，推到哪用到哪。常见品牌：也雅。", "optional", "item", "buy_for_home", "none", "medium"],
  ]),
  ...section("partner", [
    ["partner-doc-folder", "确认证件包位置", "must", "pack_now", "", "证件包放在固定位置，全家都知道在哪儿。", "core", "task", "task", "documents_folder", "small"],
    ["partner-payment", "确认支付方式和住院押金", "must", "confirm_beforehand", "", "支付方式、住院押金和医保结算属于入院确认事项，不算待产包物品。若医院明确要求实体银行卡或现金，再作为自定义物品加入证件包。", "core", "task", "task", "none", "small"],
    ["partner-car-seat", "确认安全座椅安装", "must", "pack_now", "", "用于提前熟悉宝宝返家乘车安排；选择明确适用于新生儿身高和体重的座椅，按说明书和车辆条件完成后向安装并练习卡扣。二手座椅只考虑来源可靠、无碰撞史、未召回、未过期且配件说明书齐全的产品。", "core", "task", "install_or_place", "car", "large"],
    ["partner-family-notice", "临出门通知家人/紧急联系人", "recommended", "grab_before_leaving", "", "出发时发一条消息：去哪家医院、走哪个门、谁在场。", "core", "task", "task", "last_minute", "small"],
    ["partner-id", "陪产人身份证件", "must", "grab_before_leaving", "原件 1 份", "用于陪产登记或身份核验；建议把原件一份放入陪产人随身包，并先确认医院要求。", "core", "item", "", "dad_backpack", "small"],
    ["partner-charger", "手机充电器", "must", "pack_now", "1 套", "用于陪产期间给常用设备充电；建议准备一套接口匹配的充电器和约两米长线。", "core", "item", "", "dad_backpack", "small"],
    ["partner-water-snacks", "水和零食", "recommended", "pack_now", "饮水 1-2 瓶 + 小包装零食 1-2 份", "用于陪产人等待或无法及时用餐时补充；建议准备一至两瓶饮水和一至两份易开启的小包装零食。", "core", "item", "", "dad_backpack", "medium"],
    ["partner-clothes", "换洗衣物 1 套，如需过夜", "recommended", "wash_before_pack", "换洗衣物 1 套", "用于陪产人需要过夜时换洗；建议准备一套轻便、易穿脱且适合病房温度的衣物。", "core", "item", "", "dad_backpack", "medium"],
    ["partner-toiletries", "洗漱用品，如需过夜", "recommended", "pack_now", "旅行装 1 套", "用于陪产人过夜时日常清洁；建议用一个小包分装牙刷、牙膏和小毛巾各一件。", "core", "item", "", "dad_backpack", "small"],
    ["partner-glasses", "眼镜 / 隐形眼镜用品", "optional", "grab_before_leaving", "框架眼镜 1 副 + 眼镜盒 1 个", "用于陪产期间清晰视物和轮换佩戴；建议带一副框架眼镜及保护盒，其他护理用品按个人需要准备。", "optional", "item", "", "dad_backpack", "small"],
    ["partner-medicine-list", "个人常用药清单 / 按需确认", "optional", "grab_before_leaving", "", "如有长期用药，按个人情况提前确认。", "optional", "task", "", "dad_backpack", "small"],
    ["partner-bedding", "陪护被褥 / 折叠床", "optional", "pack_now", "1 套", "用于医院允许且确需过夜陪护时休息；建议先确认病区提供情况和尺寸限制，再决定是否带一套轻便用品。", "optional", "item", "pack_existing", "car", "large"],
  ]),
  ...section("going_home", [
    ["going-home-mom-clothes", "复核妈妈出院衣物已装入病房包", "must", "confirm_beforehand", "", "出院前确认病房包里的妈妈出院衣物适合当天天气、腹部宽松且穿着舒适，不需要再准备第二套同名物品。", "core", "task", "task", "none", "small"],
    ["going-home-baby-clothes", "复核宝宝出院衣物已装入病房包", "must", "confirm_beforehand", "", "出院前确认宝宝病房包里的一主一备衣物尺码和厚度适合宝宝与当天天气，不需要重复装包。", "core", "task", "task", "none", "small"],
    ["going-home-blanket", "复核出院包被 / 保暖层", "must", "confirm_beforehand", "", "出院前从宝宝病房包中取用与天气匹配的包被或保暖层，并确认不会影响安全座椅约束带贴合。", "core", "task", "task", "none", "small"],
    ["going-home-transport", "返家交通安排", "must", "confirm_beforehand", "", "提前约好车，确认能装安全座椅，堵车时段多留余量。", "core", "task", "install_or_place", "car", "small"],
    ["going-home-car-seat", "安全座椅确认", "must", "pack_now", "", "用于宝宝出院返程时提供合适约束；确认座椅适用于新生儿身高和体重，按说明书后向安装，并在出院前复核固定状态和卡扣路径。", "core", "task", "install_or_place", "car", "large"],
  ]),
  ...section("last_minute", [
    ["last-id", "身份证件", "must", "grab_before_leaving", "", "出门前把需要携带的身份证原件放入证件包，并由陪产人按医院要求复核一次。", "core", "task", "last_minute", "last_minute", "small", false],
    ["last-medical-card", "医保卡 / 社保卡", "must", "grab_before_leaving", "", "出门前把本人医保卡或社保卡放入证件包，并确认电子凭证能够正常打开。", "core", "task", "last_minute", "last_minute", "small", false],
    ["last-maternal-book", "本地区孕产资料 / 母子健康手册", "must", "grab_before_leaving", "", "出门前把本地区要求的孕产资料或母子健康手册放入证件包，并确认纸质或电子版本可出示。", "core", "task", "last_minute", "last_minute", "small", false],
    ["last-prenatal-records", "产检资料", "must", "grab_before_leaving", "", "出门前把按日期整理好的产检本、影像和化验资料整套放入证件包。", "core", "task", "last_minute", "last_minute", "medium", false],
    ["last-phone", "手机", "must", "grab_before_leaving", "", "出门前拿上常用手机，确认电量充足，并把医院和紧急联系人置顶。", "core", "task", "last_minute", "last_minute", "small", false],
    ["last-charger", "充电器", "must", "grab_before_leaving", "", "出门前把与手机接口匹配的充电头和充电线装入随身包。", "core", "task", "last_minute", "last_minute", "small", false],
    ["last-mom-bag", "产房包和妈妈病房包放到固定位置", "must", "grab_before_leaving", "", "出门前从固定位置拿上产房包和妈妈病房包，分别拉好拉链，并按两个分区快速复核物品。", "core", "task", "last_minute", "last_minute", "large", false],
    ["last-baby-bag", "宝宝病房包放到固定位置", "must", "grab_before_leaving", "", "出门前从固定位置拿上宝宝病房包，确认住院用品、出院衣物、尿不湿和包被已经装好。", "core", "task", "last_minute", "last_minute", "large", false],
    ["last-medicine-list", "常用药清单 / 医生确认用药", "must", "grab_before_leaving", "", "出门前带上已整理的常用药清单；如有长期用药，携带和使用方式提前向医生或护士确认。", "core", "task", "last_minute", "last_minute", "small", false],
    ["last-glasses", "眼镜 / 隐形眼镜", "must", "grab_before_leaving", "", "出门前拿上框架眼镜和眼镜盒；隐形眼镜及护理用品按个人需要一并带走。", "core", "task", "last_minute", "last_minute", "small", false],
    ["last-payment", "支付 / 押金确认", "must", "grab_before_leaving", "", "出门前确认可用的支付方式、额度和押金信息，需要实体银行卡或现金时放入证件包。", "core", "task", "task", "none", "small", false],
    ["last-car-seat", "安全座椅确认", "must", "grab_before_leaving", "", "出门前确认使用新生儿适用的后向安全座椅，并按说明书检查安装方向、固定状态和卡扣路径，发现松动先重新调整。", "core", "task", "install_or_place", "car", "large", false],
  ]),
];
